"""
This type stub file was generated by pyright.
"""

import dataclasses
import numpy as np
from typing import Mapping, Optional, Union
from mediapipe.tasks.python.components.containers import detections as detections_module, landmark as landmark_module

"""MediaPipe solution drawing utils."""
_PRESENCE_THRESHOLD = ...
_VISIBILITY_THRESHOLD = ...
_BGR_CHANNELS = ...
_CONNECTION = ...
WHITE_COLOR = ...
BLACK_COLOR = ...
RED_COLOR = ...
GREEN_COLOR = ...
BLUE_COLOR = ...
@dataclasses.dataclass
class DrawingSpec:
  color: tuple[int, int, int] = ...
  thickness: int = ...
  circle_radius: int = ...


def draw_detection(image: np.ndarray, detection: detections_module.Detection, keypoint_drawing_spec: DrawingSpec = ..., bbox_drawing_spec: DrawingSpec = ...): # -> None:
  """Draws the detction bounding box and keypoints on the image.

  Args:
    image: A three channel BGR image represented as numpy ndarray.
    detection: A detection object with a bounding box.
    keypoint_drawing_spec: A DrawingSpec object that specifies the keypoints'
      drawing settings such as color, line thickness, and circle radius.
    bbox_drawing_spec: A DrawingSpec object that specifies the bounding box's
      drawing settings such as color and line thickness.

  Raises:
    ValueError: If the input image is not three channel BGR.
  """
  ...

def draw_landmarks(image: np.ndarray, landmark_list: list[landmark_module.NormalizedLandmark], connections: Optional[list[_CONNECTION]] = ..., landmark_drawing_spec: Optional[Union[DrawingSpec, Mapping[int, DrawingSpec]]] = ..., connection_drawing_spec: Union[DrawingSpec, Mapping[tuple[int, int], DrawingSpec]] = ..., is_drawing_landmarks: bool = ...): # -> None:
  """Draws the landmarks and the connections on the image.

  Args:
    image: A three channel BGR image represented as numpy ndarray.
    landmark_list: A list of normalized landmarks to be annotated on the image.
    connections: A list of landmark index tuples that specifies how landmarks to
      be connected in the drawing.
    landmark_drawing_spec: Either a DrawingSpec object or a mapping from hand
      landmarks to the DrawingSpecs that specifies the landmarks' drawing
      settings such as color, line thickness, and circle radius. If this
      argument is explicitly set to None, no landmarks will be drawn.
    connection_drawing_spec: Either a DrawingSpec object or a mapping from hand
      connections to the DrawingSpecs that specifies the connections' drawing
      settings such as color and line thickness. If this argument is explicitly
      set to None, no landmark connections will be drawn.
    is_drawing_landmarks: Whether to draw landmarks. If set false, skip drawing
      landmarks, only contours will be drawed.

  Raises:
    ValueError: If one of the followings:
      a) If the input image is not three channel BGR.
      b) If any connetions contain invalid landmark index.
  """
  ...

def draw_axis(image: np.ndarray, rotation: np.ndarray, translation: np.ndarray, focal_length: tuple[float, float] = ..., principal_point: tuple[float, float] = ..., axis_length: float = ..., axis_drawing_spec: DrawingSpec = ...): # -> None:
  """Draws the 3D axis on the image.

  Args:
    image: A three channel BGR image represented as numpy ndarray.
    rotation: Rotation matrix from object to camera coordinate frame.
    translation: Translation vector from object to camera coordinate frame.
    focal_length: camera focal length along x and y directions.
    principal_point: camera principal point in x and y.
    axis_length: length of the axis in the drawing.
    axis_drawing_spec: A DrawingSpec object that specifies the xyz axis drawing
      settings such as line thickness.

  Raises:
    ValueError: If one of the followings:
      a) If the input image is not three channel BGR.
  """
  ...

def plot_landmarks(landmark_list: list[landmark_module.NormalizedLandmark], connections: Optional[list[tuple[int, int]]] = ..., landmark_drawing_spec: DrawingSpec = ..., connection_drawing_spec: DrawingSpec = ..., elevation: int = ..., azimuth: int = ...): # -> None:
  """Plot the landmarks and the connections in matplotlib 3d.

  Args:
    landmark_list: A list of normalized landmarks to be plotted.
    connections: A list of landmark index tuples that specifies how landmarks to
      be connected.
    landmark_drawing_spec: A DrawingSpec object that specifies the landmarks'
      drawing settings such as color and line thickness.
    connection_drawing_spec: A DrawingSpec object that specifies the
      connections' drawing settings such as color and line thickness.
    elevation: The elevation from which to view the plot.
    azimuth: the azimuth angle to rotate the plot.

  Raises:
    ValueError: If any connection contains an invalid landmark index.
  """
  ...

