"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
import enum
import numpy as np
from typing import Callable, List, Optional
from mediapipe.tasks.python.components.containers import category as category_lib, landmark as landmark_lib
from mediapipe.tasks.python.core import async_result_dispatcher, base_options as base_options_lib, base_options_c as base_options_c_lib, mediapipe_c_utils, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image as image_lib, image_processing_options as image_processing_options_lib, vision_task_running_mode as running_mode_lib

"""MediaPipe face landmarker task."""
_BaseOptions = base_options_lib.BaseOptions
_RunningMode = running_mode_lib.VisionTaskRunningMode
_ImageProcessingOptions = image_processing_options_lib.ImageProcessingOptions
_CStatusFunction = mediapipe_c_utils.CStatusFunction
_AsyncResultDispatcher = async_result_dispatcher.AsyncResultDispatcher
_LiveStreamPacket = async_result_dispatcher.LiveStreamPacket
class Blendshapes(enum.IntEnum):
  """The 52 blendshape coefficients."""
  NEUTRAL = ...
  BROW_DOWN_LEFT = ...
  BROW_DOWN_RIGHT = ...
  BROW_INNER_UP = ...
  BROW_OUTER_UP_LEFT = ...
  BROW_OUTER_UP_RIGHT = ...
  CHEEK_PUFF = ...
  CHEEK_SQUINT_LEFT = ...
  CHEEK_SQUINT_RIGHT = ...
  EYE_BLINK_LEFT = ...
  EYE_BLINK_RIGHT = ...
  EYE_LOOK_DOWN_LEFT = ...
  EYE_LOOK_DOWN_RIGHT = ...
  EYE_LOOK_IN_LEFT = ...
  EYE_LOOK_IN_RIGHT = ...
  EYE_LOOK_OUT_LEFT = ...
  EYE_LOOK_OUT_RIGHT = ...
  EYE_LOOK_UP_LEFT = ...
  EYE_LOOK_UP_RIGHT = ...
  EYE_SQUINT_LEFT = ...
  EYE_SQUINT_RIGHT = ...
  EYE_WIDE_LEFT = ...
  EYE_WIDE_RIGHT = ...
  JAW_FORWARD = ...
  JAW_LEFT = ...
  JAW_OPEN = ...
  JAW_RIGHT = ...
  MOUTH_CLOSE = ...
  MOUTH_DIMPLE_LEFT = ...
  MOUTH_DIMPLE_RIGHT = ...
  MOUTH_FROWN_LEFT = ...
  MOUTH_FROWN_RIGHT = ...
  MOUTH_FUNNEL = ...
  MOUTH_LEFT = ...
  MOUTH_LOWER_DOWN_LEFT = ...
  MOUTH_LOWER_DOWN_RIGHT = ...
  MOUTH_PRESS_LEFT = ...
  MOUTH_PRESS_RIGHT = ...
  MOUTH_PUCKER = ...
  MOUTH_RIGHT = ...
  MOUTH_ROLL_LOWER = ...
  MOUTH_ROLL_UPPER = ...
  MOUTH_SHRUG_LOWER = ...
  MOUTH_SHRUG_UPPER = ...
  MOUTH_SMILE_LEFT = ...
  MOUTH_SMILE_RIGHT = ...
  MOUTH_STRETCH_LEFT = ...
  MOUTH_STRETCH_RIGHT = ...
  MOUTH_UPPER_UP_LEFT = ...
  MOUTH_UPPER_UP_RIGHT = ...
  NOSE_SNEER_LEFT = ...
  NOSE_SNEER_RIGHT = ...


class FaceLandmarksConnections:
  """The connections between face landmarks."""
  @dataclasses.dataclass
  class Connection:
    """The connection class for face landmarks."""
    start: int
    end: int
    ...
  
  
  FACE_LANDMARKS_LIPS: List[Connection] = ...
  FACE_LANDMARKS_LEFT_EYE: List[Connection] = ...
  FACE_LANDMARKS_LEFT_EYEBROW: List[Connection] = ...
  FACE_LANDMARKS_LEFT_IRIS: List[Connection] = ...
  FACE_LANDMARKS_RIGHT_EYE: List[Connection] = ...
  FACE_LANDMARKS_RIGHT_EYEBROW: List[Connection] = ...
  FACE_LANDMARKS_RIGHT_IRIS: List[Connection] = ...
  FACE_LANDMARKS_FACE_OVAL: List[Connection] = ...
  FACE_LANDMARKS_NOSE: List[Connection] = ...
  FACE_LANDMARKS_CONTOURS: List[Connection] = ...
  FACE_LANDMARKS_TESSELATION: List[Connection] = ...


class MpFaceLandmarkerResultC(ctypes.Structure):
  """The ctypes struct for MpFaceLandmarkerResult."""
  _fields_ = ...


_C_TYPES_RESULT_CALLBACK = ...
@dataclasses.dataclass
class FaceLandmarkerResult:
  """The face landmarks detection result from FaceLandmarker, where each vector element represents a single face detected in the image.

  Attributes:
    face_landmarks: Detected face landmarks in normalized image coordinates.
    face_blendshapes: Optional face blendshapes results.
    facial_transformation_matrixes: Optional facial transformation matrix.
  """
  face_landmarks: List[List[landmark_lib.NormalizedLandmark]]
  face_blendshapes: List[List[category_lib.Category]]
  facial_transformation_matrixes: List[np.ndarray]
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_struct: MpFaceLandmarkerResultC) -> FaceLandmarkerResult:
    """Creates a FaceLandmarkerResult from a ctypes struct."""
    ...
  


class MpFaceLandmarkerOptionsC(ctypes.Structure):
  """The ctypes struct for MpFaceLandmarkerOptions."""
  _fields_ = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_c_options(cls, base_options: base_options_c_lib.MpBaseOptionsC, running_mode: _RunningMode, num_faces: int, min_face_detection_confidence: float, min_face_presence_confidence: float, min_tracking_confidence: float, output_face_blendshapes: bool, output_facial_transformation_matrixes: bool, result_callback: _C_TYPES_RESULT_CALLBACK) -> MpFaceLandmarkerOptionsC:
    """Creates a MpFaceLandmarkerOptionsC object from the given options."""
    ...
  


@dataclasses.dataclass
class FaceLandmarkerOptions:
  """Options for the face landmarker task.

  Attributes:
    base_options: Base options for the face landmarker task.
    running_mode: The running mode of the task. Default to the image mode.
      FaceLandmarker has three running modes: 1) The image mode for detecting
      face landmarks on single image inputs. 2) The video mode for detecting
      face landmarks on the decoded frames of a video. 3) The live stream mode
      for detecting face landmarks on the live stream of input data, such as
      from camera. In this mode, the "result_callback" below must be specified
      to receive the detection results asynchronously.
    num_faces: The maximum number of faces that can be detected by the
      FaceLandmarker.
    min_face_detection_confidence: The minimum confidence score for the face
      detection to be considered successful.
    min_face_presence_confidence: The minimum confidence score of face presence
      score in the face landmark detection.
    min_tracking_confidence: The minimum confidence score for the face tracking
      to be considered successful.
    output_face_blendshapes: Whether FaceLandmarker outputs face blendshapes
      classification. Face blendshapes are used for rendering the 3D face model.
    output_facial_transformation_matrixes: Whether FaceLandmarker outputs facial
      transformation_matrix. Facial transformation matrix is used to transform
      the face landmarks in canonical face to the detected face, so that users
      can apply face effects on the detected landmarks.
    result_callback: The user-defined result callback for processing live stream
      data. The result callback should only be specified when the running mode
      is set to the live stream mode.
  """
  base_options: _BaseOptions
  running_mode: _RunningMode = ...
  num_faces: int = ...
  min_face_detection_confidence: float = ...
  min_face_presence_confidence: float = ...
  min_tracking_confidence: float = ...
  output_face_blendshapes: bool = ...
  output_facial_transformation_matrixes: bool = ...
  result_callback: Optional[Callable[[FaceLandmarkerResult, image_lib.Image, int], None]] = ...


_CTYPES_SIGNATURES = ...
class FaceLandmarker:
  """Class that performs face landmark detection on images."""
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  _dispatcher: _AsyncResultDispatcher
  _async_callback: _C_TYPES_RESULT_CALLBACK
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p, dispatcher: _AsyncResultDispatcher, async_callback: _C_TYPES_RESULT_CALLBACK) -> None:
    """Initializes the face landmarker.

    Args:
      lib: The dispatch library to use for the face landmarker.
      handle: The C pointer to the face landmarker.
      dispatcher: The async result handler for the face landmarker.
      async_callback: The c callback for the face landmarker.
    """
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> FaceLandmarker:
    """Creates an `FaceLandmarker` object from a TensorFlow Lite model and the default `FaceLandmarkerOptions`.

    Note that the created `FaceLandmarker` instance is in image mode, for
    detecting face landmarks on single image inputs.

    Args:
      model_path: Path to the model.

    Returns:
      `FaceLandmarker` object that's created from the model file and the
      default `FaceLandmarkerOptions`.

    Raises:
      ValueError: If failed to create `FaceLandmarker` object from the
        provided file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: FaceLandmarkerOptions) -> FaceLandmarker:
    """Creates the `FaceLandmarker` object from face landmarker options.

    Args:
      options: Options for the face landmarker task.

    Returns:
      `FaceLandmarker` object that's created from `options`.

    Raises:
      ValueError: If failed to create `FaceLandmarker` object from
        `FaceLandmarkerOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def detect(self, image: image_lib.Image, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> FaceLandmarkerResult:
    """Performs face landmark detection on the provided MediaPipe Image.

    Only use this method when the FaceLandmarker is created with the image
    running mode.

    Args:
      image: MediaPipe Image.
      image_processing_options: Options for image processing.

    Returns:
      A face landmarker result object that contains a list of face landmarks.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If face landmark detection failed to run.
    """
    ...
  
  def detect_for_video(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> FaceLandmarkerResult:
    """Performs face landmarks detection on the provided video frame.

    Only use this method when the FaceLandmarker is created with the video
    running mode.

    Only use this method when the FaceLandmarker is created with the video
    running mode. It's required to provide the video frame's timestamp (in
    milliseconds) along with the video frame. The input timestamps should be
    monotonically increasing for adjacent calls of this method.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input video frame in milliseconds.
      image_processing_options: Options for image processing.

    Returns:
      The face landmarks detection results.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If face landmarker detection failed to run.
    """
    ...
  
  def detect_async(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> None:
    """Sends live image data to perform face landmarks detection.

    The results will be available via the "result_callback" provided in the
    FaceLandmarkerOptions. Only use this method when the FaceLandmarker is
    created with the live stream running mode.

    Only use this method when the FaceLandmarker is created with the live
    stream running mode. The input timestamps should be monotonically increasing
    for adjacent calls of this method. This method will return immediately after
    the input image is accepted. The results will be available via the
    `result_callback` provided in the `FaceLandmarkerOptions`. The
    `detect_async` method is designed to process live stream data such as
    camera input. To lower the overall latency, face landmarker may drop the
    input images if needed. In other words, it's not guaranteed to have output
    per input image.

    The `result_callback` provides:
      - The face landmarks detection results.
      - The input image that the face landmarker runs on.
      - The input timestamp in milliseconds.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input image in milliseconds.
      image_processing_options: Options for image processing.

    Raises:
      ValueError: If the current input timestamp is smaller than what the
        face landmarker has already processed.
      RuntimeError: If the face landmark detection failed to run.
    """
    ...
  
  def close(self): # -> None:
    """Closes the FaceLandmarker."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager.

    Args:
      exc_type: The exception type that caused the context manager to exit.
      exc_value: The exception value that caused the context manager to exit.
      traceback: The exception traceback that caused the context manager to
        exit.

    Raises:
      RuntimeError: If the MediaPipe FaceDetector task failed to close.
    """
    ...
  
  def __del__(self): # -> None:
    ...
  


