"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
from typing import Callable, Optional
from mediapipe.tasks.python.components.containers import detections as detections_module
from mediapipe.tasks.python.core import async_result_dispatcher, base_options as base_options_module, base_options_c as base_options_c_module, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image as image_module, image_processing_options as image_processing_options_module, vision_task_running_mode as running_mode_module

"""MediaPipe face detector task."""
FaceDetectorResult = ...
_RunningMode = running_mode_module.VisionTaskRunningMode
_BaseOptions = base_options_module.BaseOptions
_ImageProcessingOptions = image_processing_options_module.ImageProcessingOptions
_C_TYPES_RESULT_CALLBACK = ...
class MpFaceDetectorOptionsC(ctypes.Structure):
  """C types for MpFaceDetectorOptions."""
  _fields_ = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_c_options(cls, base_options: base_options_c_module.MpBaseOptionsC, running_mode: _RunningMode, min_detection_confidence: float, min_suppression_threshold: float, result_callback: _C_TYPES_RESULT_CALLBACK) -> MpFaceDetectorOptionsC:
    """Creates a MpFaceDetectorOptionsC object from the given options."""
    ...
  


_CTYPES_SIGNATURES = ...
@dataclasses.dataclass
class FaceDetectorOptions:
  """Options for the face detector task.

  Attributes:
    base_options: Base options for the face detector task.
    running_mode: The running mode of the task. Default to the image mode. Face
      detector task has three running modes: 1) The image mode for detecting
      faces on single image inputs. 2) The video mode for detecting faces on the
      decoded frames of a video. 3) The live stream mode for detecting faces on
      a live stream of input data, such as from camera.
    min_detection_confidence: The minimum confidence score for the face
      detection to be considered successful.
    min_suppression_threshold: The minimum non-maximum-suppression threshold for
      face detection to be considered overlapped.
    result_callback: The user-defined result callback for processing live stream
      data. The result callback should only be specified when the running mode
      is set to the live stream mode.
  """
  base_options: _BaseOptions
  running_mode: _RunningMode = ...
  min_detection_confidence: float = ...
  min_suppression_threshold: float = ...
  result_callback: Optional[Callable[[detections_module.DetectionResult, image_module.Image, int], None]] = ...


class FaceDetector:
  """Class that performs face detection on images."""
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  _dispatcher: async_result_dispatcher.AsyncResultDispatcher
  _async_callback: _C_TYPES_RESULT_CALLBACK
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p, dispatcher: async_result_dispatcher.AsyncResultDispatcher, async_callback: _C_TYPES_RESULT_CALLBACK) -> None:
    """Initializes the face detector.

    Args:
      lib: The dispatch library to use for the face detector.
      handle: The C pointer to the face detector.
      dispatcher: The async result handler for the face detector.
      async_callback: The c callback for the face detector.
    """
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> FaceDetector:
    """Creates an `FaceDetector` object from a TensorFlow Lite model and the default `FaceDetectorOptions`.

    Note that the created `FaceDetector` instance is in image mode, for
    detecting faces on single image inputs.

    Args:
      model_path: Path to the model.

    Returns:
      `FaceDetector` object that's created from the model file and the default
      `FaceDetectorOptions`.

    Raises:
      ValueError: If failed to create `FaceDetector` object from the provided
        file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: FaceDetectorOptions) -> FaceDetector:
    """Creates the `FaceDetector` object from face detector options.

    Args:
      options: Options for the face detector task.

    Returns:
      `FaceDetector` object that's created from `options`.

    Raises:
      ValueError: If failed to create `FaceDetector` object from
        `FaceDetectorOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def detect(self, image: image_module.Image, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> FaceDetectorResult:
    """Performs face detection on the provided MediaPipe Image.

    Only use this method when the FaceDetector is created with the image
    running mode.

    Args:
      image: MediaPipe Image.
      image_processing_options: Options for image processing.

    Returns:
      A face detection result object that contains a list of face detections,
      each detection has a bounding box that is expressed in the unrotated input
      frame of reference coordinates system, i.e. in `[0,image_width) x [0,
      image_height)`, which are the dimensions of the underlying image data.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If face detection failed to run.
    """
    ...
  
  def detect_for_video(self, image: image_module.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> detections_module.DetectionResult:
    """Performs face detection on the provided video frames.

    Only use this method when the FaceDetector is created with the video
    running mode. It's required to provide the video frame's timestamp (in
    milliseconds) along with the video frame. The input timestamps should be
    monotonically increasing for adjacent calls of this method.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input video frame in milliseconds.
      image_processing_options: Options for image processing.

    Returns:
      A face detection result object that contains a list of face detections,
      each detection has a bounding box that is expressed in the unrotated input
      frame of reference coordinates system, i.e. in `[0,image_width) x [0,
      image_height)`, which are the dimensions of the underlying image data.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If face detection failed to run.
    """
    ...
  
  def detect_async(self, image: image_module.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> None:
    """Sends live image data (an Image with a unique timestamp) to perform face detection.

    Only use this method when the FaceDetector is created with the live stream
    running mode. The input timestamps should be monotonically increasing for
    adjacent calls of this method. This method will return immediately after the
    input image is accepted. The results will be available via the
    `result_callback` provided in the `FaceDetectorOptions`. The
    `detect_async` method is designed to process live stream data such as camera
    input. To lower the overall latency, face detector may drop the input
    images if needed. In other words, it's not guaranteed to have output per
    input image.

    The `result_callback` provides:
      - A face detection result object that contains a list of face detections,
        each detection has a bounding box that is expressed in the unrotated
        input frame of reference coordinates system,
        i.e. in `[0,image_width) x [0,image_height)`, which are the dimensions
        of the underlying image data.
      - The input image that the face detector runs on.
      - The input timestamp in milliseconds.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input image in milliseconds.
      image_processing_options: Options for image processing.

    Raises:
      ValueError: If the current input timestamp is smaller than what the face
        detector has already processed.
      RuntimeError: If face detection failed to initialize.
    """
    ...
  
  def close(self): # -> None:
    """Shuts down the MediaPipe task instance."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager.

    Args:
      exc_type: The exception type that caused the exit.
      exc_value: The exception value that caused the exit.
      traceback: The exception traceback that caused the exit.

    Raises:
      RuntimeError: If the MediaPipe FaceDetector task failed to close.
    """
    ...
  
  def __del__(self): # -> None:
    ...
  


