"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
import enum
from typing import Callable, List, Optional
from mediapipe.tasks.python.components.containers import category, landmark
from mediapipe.tasks.python.core import async_result_dispatcher, base_options as base_options_lib, base_options_c, mediapipe_c_utils, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image as image_lib, image_processing_options as image_processing_options_lib, vision_task_running_mode

"""MediaPipe hand landmarker task."""
_BaseOptions = base_options_lib.BaseOptions
_RunningMode = vision_task_running_mode.VisionTaskRunningMode
_ImageProcessingOptions = image_processing_options_lib.ImageProcessingOptions
_CFunction = mediapipe_c_utils.CFunction
_AsyncResultDispatcher = async_result_dispatcher.AsyncResultDispatcher
class MpHandLandmarkerResultC(ctypes.Structure):
  """The hand landmarker result from HandLandmarker in ctypes."""
  _fields_ = ...


_C_TYPES_RESULT_CALLBACK = ...
class MpHandLandmarkerOptionsC(ctypes.Structure):
  """The hand landmarker options used in the C API."""
  _fields_ = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_c_options(cls, base_options: base_options_c.MpBaseOptionsC, running_mode: _RunningMode, num_hands: int, min_hand_detection_confidence: float, min_hand_presence_confidence: float, min_tracking_confidence: float, result_callback: _C_TYPES_RESULT_CALLBACK) -> MpHandLandmarkerOptionsC:
    """Creates a MpHandLandmarkerOptionsC object from the given options."""
    ...
  


_CTYPES_SIGNATURES = ...
class HandLandmark(enum.IntEnum):
  """The 21 hand landmarks."""
  WRIST = ...
  THUMB_CMC = ...
  THUMB_MCP = ...
  THUMB_IP = ...
  THUMB_TIP = ...
  INDEX_FINGER_MCP = ...
  INDEX_FINGER_PIP = ...
  INDEX_FINGER_DIP = ...
  INDEX_FINGER_TIP = ...
  MIDDLE_FINGER_MCP = ...
  MIDDLE_FINGER_PIP = ...
  MIDDLE_FINGER_DIP = ...
  MIDDLE_FINGER_TIP = ...
  RING_FINGER_MCP = ...
  RING_FINGER_PIP = ...
  RING_FINGER_DIP = ...
  RING_FINGER_TIP = ...
  PINKY_MCP = ...
  PINKY_PIP = ...
  PINKY_DIP = ...
  PINKY_TIP = ...


class HandLandmarksConnections:
  """The connections between hand landmarks."""
  @dataclasses.dataclass
  class Connection:
    """The connection class for hand landmarks."""
    start: int
    end: int
    ...
  
  
  HAND_PALM_CONNECTIONS: List[Connection] = ...
  HAND_THUMB_CONNECTIONS: List[Connection] = ...
  HAND_INDEX_FINGER_CONNECTIONS: List[Connection] = ...
  HAND_MIDDLE_FINGER_CONNECTIONS: List[Connection] = ...
  HAND_RING_FINGER_CONNECTIONS: List[Connection] = ...
  HAND_PINKY_FINGER_CONNECTIONS: List[Connection] = ...
  HAND_CONNECTIONS: List[Connection] = ...


@dataclasses.dataclass
class HandLandmarkerResult:
  """The hand landmarks result from HandLandmarker, where each vector element represents a single hand detected in the image.

  Attributes:
    handedness: Classification of handedness.
    hand_landmarks: Detected hand landmarks in normalized image coordinates.
    hand_world_landmarks: Detected hand landmarks in world coordinates.
  """
  handedness: List[List[category.Category]]
  hand_landmarks: List[List[landmark.NormalizedLandmark]]
  hand_world_landmarks: List[List[landmark.Landmark]]
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_obj: MpHandLandmarkerResultC) -> HandLandmarkerResult:
    """Creates a `HandLandmarkerResult` from a `MpHandLandmarkerResultC`."""
    ...
  


@dataclasses.dataclass
class HandLandmarkerOptions:
  """Options for the hand landmarker task.

  Attributes:
    base_options: Base options for the hand landmarker task.
    running_mode: The running mode of the task. Default to the image mode.
      HandLandmarker has three running modes: 1) The image mode for detecting
      hand landmarks on single image inputs. 2) The video mode for detecting
      hand landmarks on the decoded frames of a video. 3) The live stream mode
      for detecting hand landmarks on the live stream of input data, such as
      from camera. In this mode, the "result_callback" below must be specified
      to receive the detection results asynchronously.
    num_hands: The maximum number of hands can be detected by the hand
      landmarker.
    min_hand_detection_confidence: The minimum confidence score for the hand
      detection to be considered successful.
    min_hand_presence_confidence: The minimum confidence score of hand presence
      score in the hand landmark detection.
    min_tracking_confidence: The minimum confidence score for the hand tracking
      to be considered successful.
    result_callback: The user-defined result callback for processing live stream
      data. The result callback should only be specified when the running mode
      is set to the live stream mode.
  """
  base_options: _BaseOptions
  running_mode: _RunningMode = ...
  num_hands: int = ...
  min_hand_detection_confidence: float = ...
  min_hand_presence_confidence: float = ...
  min_tracking_confidence: float = ...
  result_callback: Optional[Callable[[HandLandmarkerResult, image_lib.Image, int], None]] = ...


class HandLandmarker:
  """Class that performs hand landmarks detection on images."""
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  _dispatcher: _AsyncResultDispatcher
  _async_callback: _C_TYPES_RESULT_CALLBACK
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p, dispatcher: _AsyncResultDispatcher, async_callback: _C_TYPES_RESULT_CALLBACK) -> None:
    """Initializes the hand landmarker.

    Args:
      lib: The dispatch library to use for the hand landmarker.
      handle: The C pointer to the hand landmarker.
      dispatcher: The async result handler for the hand landmarker.
      async_callback: The c callback for the hand landmarker.
    """
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> HandLandmarker:
    """Creates an `HandLandmarker` object from a TensorFlow Lite model and the default `HandLandmarkerOptions`.

    Note that the created `HandLandmarker` instance is in image mode, for
    detecting hand landmarks on single image inputs.

    Args:
      model_path: Path to the model.

    Returns:
      `HandLandmarker` object that's created from the model file and the
      default `HandLandmarkerOptions`.

    Raises:
      ValueError: If failed to create `HandLandmarker` object from the
        provided file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: HandLandmarkerOptions) -> HandLandmarker:
    """Creates the `HandLandmarker` object from hand landmarker options.

    Args:
      options: Options for the hand landmarker task.

    Returns:
      `HandLandmarker` object that's created from `options`.

    Raises:
      ValueError: If failed to create `HandLandmarker` object from
        `HandLandmarkerOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def detect(self, image: image_lib.Image, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> HandLandmarkerResult:
    """Performs hand landmarks detection on the given image.

    Only use this method when the HandLandmarker is created with the image
    running mode.

    The image can be of any size with format RGB or RGBA.
    TODO: Describes how the input image will be preprocessed after the yuv
    support is implemented.

    Args:
      image: MediaPipe Image.
      image_processing_options: Options for image processing.

    Returns:
      The hand landmarks detection results.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If hand landmarker detection failed to run.
    """
    ...
  
  def detect_for_video(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> HandLandmarkerResult:
    """Performs hand landmarks detection on the provided video frame.

    Only use this method when the HandLandmarker is created with the video
    running mode.

    Only use this method when the HandLandmarker is created with the video
    running mode. It's required to provide the video frame's timestamp (in
    milliseconds) along with the video frame. The input timestamps should be
    monotonically increasing for adjacent calls of this method.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input video frame in milliseconds.
      image_processing_options: Options for image processing.

    Returns:
      The hand landmarks detection results.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If hand landmarker detection failed to run.
    """
    ...
  
  def detect_async(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> None:
    """Sends live image data to perform hand landmarks detection.

    The results will be available via the "result_callback" provided in the
    HandLandmarkerOptions. Only use this method when the HandLandmarker is
    created with the live stream running mode.

    Only use this method when the HandLandmarker is created with the live
    stream running mode. The input timestamps should be monotonically increasing
    for adjacent calls of this method. This method will return immediately after
    the input image is accepted. The results will be available via the
    `result_callback` provided in the `HandLandmarkerOptions`. The
    `detect_async` method is designed to process live stream data such as
    camera input. To lower the overall latency, hand landmarker may drop the
    input images if needed. In other words, it's not guaranteed to have output
    per input image.

    The `result_callback` provides:
      - The hand landmarks detection results.
      - The input image that the hand landmarker runs on.
      - The input timestamp in milliseconds.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input image in milliseconds.
      image_processing_options: Options for image processing.

    Raises:
      ValueError: If the current input timestamp is smaller than what the
        hand landmarker has already processed.
      RuntimeError: If hand landmarker detection failed to initialize.
    """
    ...
  
  def close(self): # -> None:
    """Shuts down the MediaPipe task instance."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager.

    Args:
      exc_type: The exception type that caused the exit.
      exc_value: The exception value that caused the exit.
      traceback: The exception traceback that caused the exit.

    Raises:
      RuntimeError: If the MediaPipe HandLandmarker task failed to close.
    """
    ...
  
  def __del__(self): # -> None:
    ...
  


