"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
from typing import Callable, List, Optional
from mediapipe.tasks.python.components.containers import category as category_lib, landmark as landmark_lib
from mediapipe.tasks.python.core import async_result_dispatcher, base_options as base_options_lib, base_options_c as base_options_c_lib, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image as image_lib, image_processing_options as image_processing_options_lib, vision_task_running_mode as running_mode_lib

"""MediaPipe holistic landmarker task."""
_BaseOptions = base_options_lib.BaseOptions
_RunningMode = running_mode_lib.VisionTaskRunningMode
_ImageProcessingOptions = image_processing_options_lib.ImageProcessingOptions
_AsyncResultDispatcher = async_result_dispatcher.AsyncResultDispatcher
_LiveStreamPacket = async_result_dispatcher.LiveStreamPacket
class MpHolisticLandmarkerResultC(ctypes.Structure):
  """The ctypes struct for MpHolisticLandmarkerResult."""
  _fields_ = ...


_C_TYPES_RESULT_CALLBACK = ...
@dataclasses.dataclass
class HolisticLandmarkerResult:
  """The holistic landmarks result from HolisticLandmarker, where each vector element represents a single holistic detected in the image.

  Attributes:
    face_landmarks: Detected face landmarks in normalized image coordinates.
    pose_landmarks: Detected pose landmarks in normalized image coordinates.
    pose_world_landmarks: Detected pose world landmarks in image coordinates.
    left_hand_landmarks: Detected left hand landmarks in normalized image
      coordinates.
    left_hand_world_landmarks: Detected left hand landmarks in image
      coordinates.
    right_hand_landmarks: Detected right hand landmarks in normalized image
      coordinates.
    right_hand_world_landmarks: Detected right hand landmarks in image
      coordinates.
    face_blendshapes: Optional face blendshapes.
    segmentation_mask: Optional segmentation mask for pose.
  """
  face_landmarks: List[landmark_lib.NormalizedLandmark]
  pose_landmarks: List[landmark_lib.NormalizedLandmark]
  pose_world_landmarks: List[landmark_lib.Landmark]
  left_hand_landmarks: List[landmark_lib.NormalizedLandmark]
  left_hand_world_landmarks: List[landmark_lib.Landmark]
  right_hand_landmarks: List[landmark_lib.NormalizedLandmark]
  right_hand_world_landmarks: List[landmark_lib.Landmark]
  face_blendshapes: Optional[List[category_lib.Category]] = ...
  segmentation_mask: Optional[image_lib.Image] = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_struct: MpHolisticLandmarkerResultC) -> HolisticLandmarkerResult:
    """Creates a `HolisticLandmarkerResult` object from the given ctypes struct."""
    ...
  


class MpHolisticLandmarkerOptionsC(ctypes.Structure):
  """The ctypes struct for MpHolisticLandmarkerOptions."""
  _fields_ = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_c_options(cls, base_options: base_options_c_lib.MpBaseOptionsC, running_mode: _RunningMode, min_face_detection_confidence: float, min_face_suppression_threshold: float, min_face_landmarks_confidence: float, min_pose_detection_confidence: float, min_pose_suppression_threshold: float, min_pose_landmarks_confidence: float, min_hand_landmarks_confidence: float, output_face_blendshapes: bool, output_segmentation_masks: bool, result_callback: _C_TYPES_RESULT_CALLBACK) -> MpHolisticLandmarkerOptionsC:
    """Creates a MpHolisticLandmarkerOptionsC object from the given options."""
    ...
  


@dataclasses.dataclass
class HolisticLandmarkerOptions:
  """Options for the holistic landmarker task.

  Attributes:
    base_options: Base options for the holistic landmarker task.
    running_mode: The running mode of the task. Default to the image mode.
      HolisticLandmarker has three running modes: 1) The image mode for
      detecting holistic landmarks on single image inputs. 2) The video mode for
      detecting holistic landmarks on the decoded frames of a video. 3) The live
      stream mode for detecting holistic landmarks on the live stream of input
      data, such as from camera. In this mode, the "result_callback" below must
      be specified to receive the detection results asynchronously.
    min_face_detection_confidence: The minimum confidence score for the face
      detection to be considered successful.
    min_face_suppression_threshold: The minimum non-maximum-suppression
      threshold for face detection to be considered overlapped.
    min_face_landmarks_confidence: The minimum confidence score for the face
      landmark detection to be considered successful.
    min_pose_detection_confidence: The minimum confidence score for the pose
      detection to be considered successful.
    min_pose_suppression_threshold: The minimum non-maximum-suppression
      threshold for pose detection to be considered overlapped.
    min_pose_landmarks_confidence: The minimum confidence score for the pose
      landmark detection to be considered successful.
    min_hand_landmarks_confidence: The minimum confidence score for the hand
      landmark detection to be considered successful.
    output_face_blendshapes: Whether HolisticLandmarker outputs face blendshapes
      classification. Face blendshapes are used for rendering the 3D face model.
    output_segmentation_mask: whether to output segmentation masks.
    result_callback: The user-defined result callback for processing live stream
      data. The result callback should only be specified when the running mode
      is set to the live stream mode.
  """
  base_options: _BaseOptions
  running_mode: _RunningMode = ...
  min_face_detection_confidence: float = ...
  min_face_suppression_threshold: float = ...
  min_face_landmarks_confidence: float = ...
  min_pose_detection_confidence: float = ...
  min_pose_suppression_threshold: float = ...
  min_pose_landmarks_confidence: float = ...
  min_hand_landmarks_confidence: float = ...
  output_face_blendshapes: bool = ...
  output_segmentation_mask: bool = ...
  result_callback: Optional[Callable[[HolisticLandmarkerResult, image_lib.Image, int], None]] = ...


_CTYPES_SIGNATURES = ...
class HolisticLandmarker:
  """Class that performs holistic landmarks detection on images."""
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  _dispatcher: _AsyncResultDispatcher
  _async_callback: _C_TYPES_RESULT_CALLBACK
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p, dispatcher: _AsyncResultDispatcher, async_callback: _C_TYPES_RESULT_CALLBACK) -> None:
    """Initializes the holistic landmarker.

    Args:
      lib: The dispatch library to use for the holistic landmarker.
      handle: The C pointer to the holistic landmarker.
      dispatcher: The async result handler for the holistic landmarker.
      async_callback: The c callback for the holistic landmarker.
    """
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> HolisticLandmarker:
    """Creates an `HolisticLandmarker` object from a TensorFlow Lite model and the default `HolisticLandmarkerOptions`.

    Note that the created `HolisticLandmarker` instance is in image mode, for
    detecting holistic landmarks on single image inputs.

    Args:
      model_path: Path to the model.

    Returns:
      `HolisticLandmarker` object that's created from the model file and the
      default `HolisticLandmarkerOptions`.

    Raises:
      ValueError: If failed to create `HolisticLandmarker` object from the
        provided file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: HolisticLandmarkerOptions) -> HolisticLandmarker:
    """Creates the `HolisticLandmarker` object from holistic landmarker options.

    Args:
      options: Options for the holistic landmarker task.

    Returns:
      `HolisticLandmarker` object that's created from `options`.

    Raises:
      ValueError: If failed to create `HolisticLandmarker` object from
        `HolisticLandmarkerOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def detect(self, image: image_lib.Image, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> HolisticLandmarkerResult:
    """Performs holistic landmarks detection on the given image.

    Only use this method when the HolisticLandmarker is created with the image
    running mode.

    The image can be of any size with format RGB or RGBA.

    Args:
      image: MediaPipe Image.
      image_processing_options: Options for image processing.

    Returns:
      The holistic landmarks detection results.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If holistic landmarker detection failed to run.
    """
    ...
  
  def detect_for_video(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> HolisticLandmarkerResult:
    """Performs holistic landmarks detection on the provided video frame.

    Only use this method when the HolisticLandmarker is created with the video
    running mode.

    Only use this method when the HolisticLandmarker is created with the video
    running mode. It's required to provide the video frame's timestamp (in
    milliseconds) along with the video frame. The input timestamps should be
    monotonically increasing for adjacent calls of this method.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input video frame in milliseconds.
      image_processing_options: Options for image processing.

    Returns:
      The holistic landmarks detection results.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If holistic landmarker detection failed to run.
    """
    ...
  
  def detect_async(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> None:
    """Sends live image data to perform holistic landmarks detection.

    The results will be available via the "result_callback" provided in the
    HolisticLandmarkerOptions. Only use this method when the HolisticLandmarker
    is
    created with the live stream running mode.

    Only use this method when the HolisticLandmarker is created with the live
    stream running mode. The input timestamps should be monotonically increasing
    for adjacent calls of this method. This method will return immediately after
    the input image is accepted. The results will be available via the
    `result_callback` provided in the `HolisticLandmarkerOptions`. The
    `detect_async` method is designed to process live stream data such as
    camera input. To lower the overall latency, holistic landmarker may drop the
    input images if needed. In other words, it's not guaranteed to have output
    per input image.

    The `result_callback` provides:
      - The holistic landmarks detection results.
      - The input image that the holistic landmarker runs on.
      - The input timestamp in milliseconds.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input image in milliseconds.
      image_processing_options: Options for image processing.

    Raises:
      ValueError: If the current input timestamp is smaller than what the
      holistic landmarker has already processed.
    """
    ...
  
  def close(self): # -> None:
    """Closes the HolisticLandmarker."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager."""
    ...
  
  def __del__(self): # -> None:
    ...
  


