"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
from typing import Callable, Optional
from mediapipe.tasks.python.core import async_result_dispatcher, base_options as base_options_module, base_options_c, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image as image_module, image_processing_options as image_processing_options_module, vision_task_running_mode as running_mode_module

"""MediaPipe image segmenter task."""
_BaseOptions = base_options_module.BaseOptions
_ImageProcessingOptions = image_processing_options_module.ImageProcessingOptions
_RunningMode = running_mode_module.VisionTaskRunningMode
_AsyncResultDispatcher = async_result_dispatcher.AsyncResultDispatcher
class MpStringListC(ctypes.Structure):
  _fields_ = ...


class MpImageSegmenterResultC(ctypes.Structure):
  _fields_ = ...


_C_TYPES_RESULT_CALLBACK = ...
class MpImageSegmenterOptionsC(ctypes.Structure):
  """C types for MpImageSegmenterOptions."""
  _fields_ = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_c_options(cls, base_options: base_options_c.MpBaseOptionsC, running_mode: _RunningMode, output_confidence_masks: bool, output_category_mask: bool, result_callback: _C_TYPES_RESULT_CALLBACK) -> MpImageSegmenterOptionsC:
    """Creates an MpImageSegmenterOptionsC object from the given options."""
    ...
  


_CTYPES_SIGNATURES = ...
@dataclasses.dataclass
class ImageSegmenterResult:
  """Output result of ImageSegmenter.

  confidence_masks: multiple masks of float image where, for each mask, each
  pixel represents the prediction confidence, usually in the [0, 1] range.

  category_mask: a category mask of uint8 image where each pixel represents the
  class which the pixel in the original image was predicted to belong to.
  """
  confidence_masks: Optional[list[image_module.Image]] = ...
  category_mask: Optional[image_module.Image] = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_result: MpImageSegmenterResultC) -> ImageSegmenterResult:
    """Creates an `ImageSegmenterResult` object from the given ctypes struct."""
    ...
  


@dataclasses.dataclass
class ImageSegmenterOptions:
  """Options for the image segmenter task.

  Attributes:
    base_options: Base options for the image segmenter task.
    running_mode: The running mode of the task. Default to the image mode. Image
      segmenter task has three running modes: 1) The image mode for segmenting
      objects on single image inputs. 2) The video mode for segmenting objects
      on the decoded frames of a video. 3) The live stream mode for segmenting
      objects on a live stream of input data, such as from camera.
    output_confidence_masks: Whether to output confidence masks.
    output_category_mask: Whether to output category mask.
    result_callback: The user-defined result callback for processing live stream
      data. The result callback should only be specified when the running mode
      is set to the live stream mode.
  """
  base_options: _BaseOptions
  running_mode: _RunningMode = ...
  output_confidence_masks: bool = ...
  output_category_mask: bool = ...
  result_callback: Optional[Callable[[ImageSegmenterResult, image_module.Image, int], None]] = ...


class ImageSegmenter:
  """Class that performs image segmentation on images.

  The API expects a TFLite model with mandatory TFLite Model Metadata.

  Input tensor:
    (kTfLiteUInt8/kTfLiteFloat32)
    - image input of size `[batch x height x width x channels]`.
    - batch inference is not supported (`batch` is required to be 1).
    - RGB and greyscale inputs are supported (`channels` is required to be
      1 or 3).
    - if type is kTfLiteFloat32, NormalizationOptions are required to be
      attached to the metadata for input normalization.
  Output tensors:
    (kTfLiteUInt8/kTfLiteFloat32)
    - list of segmented masks.
    - if `output_category_mask` is True, uint8 Image, Image vector of size 1.
    - if `output_confidence_masks` is True, float32 Image list of size
      `channels`.
    - batch is always 1

  An example of such model can be found at:
  https://tfhub.dev/tensorflow/lite-model/deeplabv3/1/metadata/2
  """
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  _dispatcher: _AsyncResultDispatcher
  _async_callback: _C_TYPES_RESULT_CALLBACK
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p, dispatcher: _AsyncResultDispatcher, async_callback: _C_TYPES_RESULT_CALLBACK) -> None:
    """Initializes the `ImageSegmenter` object.

    Args:
      lib: The dispatch library to use for the image segmenter.
      handle: The C pointer to the image segmenter.
      dispatcher: The async result handler for the image segmenter.
      async_callback: The c callback for the image segmenter.
    """
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> ImageSegmenter:
    """Creates an `ImageSegmenter` object from a TensorFlow Lite model and the default `ImageSegmenterOptions`.

    Note that the created `ImageSegmenter` instance is in image mode, for
    performing image segmentation on single image inputs.

    Args:
      model_path: Path to the model.

    Returns:
      `ImageSegmenter` object that's created from the model file and the default
      `ImageSegmenterOptions`.

    Raises:
      ValueError: If failed to create `ImageSegmenter` object from the provided
        file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: ImageSegmenterOptions) -> ImageSegmenter:
    """Creates the `ImageSegmenter` object from image segmenter options.

    Args:
      options: Options for the image segmenter task.

    Returns:
      `ImageSegmenter` object that's created from `options`.

    Raises:
      ValueError: If failed to create `ImageSegmenter` object from
        `ImageSegmenterOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def segment(self, image: image_module.Image, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> ImageSegmenterResult:
    """Performs the actual segmentation task on the provided MediaPipe Image.

    Args:
      image: MediaPipe Image.
      image_processing_options: Options for image processing.

    Returns:
      If the output_type is CATEGORY_MASK, the returned vector of images is
      per-category segmented image mask.
      If the output_type is CONFIDENCE_MASK, the returned vector of images
      contains only one confidence image mask. A segmentation result object that
      contains a list of segmentation masks as images.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If image segmentation failed to run.
    """
    ...
  
  def segment_for_video(self, image: image_module.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> ImageSegmenterResult:
    """Performs segmentation on the provided video frames.

    Only use this method when the ImageSegmenter is created with the video
    running mode. It's required to provide the video frame's timestamp (in
    milliseconds) along with the video frame. The input timestamps should be
    monotonically increasing for adjacent calls of this method.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input video frame in milliseconds.
      image_processing_options: Options for image processing.

    Returns:
      If the output_type is CATEGORY_MASK, the returned vector of images is
      per-category segmented image mask.
      If the output_type is CONFIDENCE_MASK, the returned vector of images
      contains only one confidence image mask. A segmentation result object that
      contains a list of segmentation masks as images.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If image segmentation failed to run.
    """
    ...
  
  def segment_async(self, image: image_module.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> None:
    """Sends live image data (an Image with a unique timestamp) to perform image segmentation.

    Only use this method when the ImageSegmenter is created with the live stream
    running mode. The input timestamps should be monotonically increasing for
    adjacent calls of this method. This method will return immediately after the
    input image is accepted. The results will be available via the
    `result_callback` provided in the `ImageSegmenterOptions`. The
    `segment_async` method is designed to process live stream data such as
    camera input. To lower the overall latency, image segmenter may drop the
    input images if needed. In other words, it's not guaranteed to have output
    per input image.

    The `result_callback` prvoides:
      - A segmentation result object that contains a list of segmentation masks
        as images.
      - The input image that the image segmenter runs on.
      - The input timestamp in milliseconds.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input image in milliseconds.
      image_processing_options: Options for image processing.

    Raises:
      ValueError: If the current input timestamp is smaller than what the image
        segmenter has already processed.
    """
    ...
  
  @property
  def labels(self) -> list[str]:
    """Get the category label list the ImageSegmenter can recognize.

    For CATEGORY_MASK type, the index in the category mask corresponds to the
    category in the label list.
    For CONFIDENCE_MASK type, the output mask list at index corresponds to the
    category in the label list.

    If there is no label map provided in the model file, empty label list is
    returned.
    """
    ...
  
  def close(self): # -> None:
    """Closes ImageSegmenter."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Closes ImageSegmenters and exits the context manager.

    Args:
      exc_type: The exception type that caused the context manager to exit.
      exc_value: The exception value that caused the context manager to exit.
      traceback: The exception traceback that caused the context manager to
        exit.

    Raises:
      RuntimeError: If the MediaPipe Gesture Recognizer task failed to
      close.
    """
    ...
  
  def __del__(self): # -> None:
    ...
  


