"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
from typing import Callable, List, Optional
from mediapipe.tasks.python.components.processors import classifier_options_c
from mediapipe.tasks.python.core import async_result_dispatcher, base_options as base_options_module, base_options_c, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image as image_lib, image_processing_options as image_processing_options_module, vision_task_running_mode as running_mode_module

"""MediaPipe image classifier task."""
ImageClassifierResult = ...
_BaseOptions = base_options_module.BaseOptions
_ClassifierOptions = ...
_RunningMode = running_mode_module.VisionTaskRunningMode
_ImageProcessingOptions = image_processing_options_module.ImageProcessingOptions
_AsyncResultDispatcher = async_result_dispatcher.AsyncResultDispatcher
_C_TYPES_RESULT_CALLBACK = ...
class MpImageClassifierOptionsC(ctypes.Structure):
  """The ctypes struct for MpImageClassifierOptions."""
  _fields_ = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_c_options(cls, base_options: base_options_c.MpBaseOptionsC, running_mode: _RunningMode, classifier_options: classifier_options_c.MpClassifierOptionsC, result_callback: _C_TYPES_RESULT_CALLBACK) -> MpImageClassifierOptionsC:
    """Creates an MpImageClassifierOptionsC object from the given options."""
    ...
  


_CTYPES_SIGNATURES = ...
@dataclasses.dataclass
class ImageClassifierOptions:
  """Options for the image classifier task.

  Attributes:
    base_options: Base options for the image classifier task.
    running_mode: The running mode of the task. Default to the image mode. Image
      classifier task has three running modes: 1) The image mode for classifying
      objects on single image inputs. 2) The video mode for classifying objects
      on the decoded frames of a video. 3) The live stream mode for classifying
      objects on a live stream of input data, such as from camera.
    display_names_locale: The locale to use for display names specified through
      the TFLite Model Metadata.
    max_results: The maximum number of top-scored classification results to
      return.
    score_threshold: Overrides the ones provided in the model metadata. Results
      below this value are rejected.
    category_allowlist: Allowlist of category names. If non-empty,
      classification results whose category name is not in this set will be
      filtered out. Duplicate or unknown category names are ignored. Mutually
      exclusive with `category_denylist`.
    category_denylist: Denylist of category names. If non-empty, classification
      results whose category name is in this set will be filtered out. Duplicate
      or unknown category names are ignored. Mutually exclusive with
      `category_allowlist`.
    result_callback: The user-defined result callback for processing live stream
      data. The result callback should only be specified when the running mode
      is set to the live stream mode.
  """
  base_options: _BaseOptions
  running_mode: _RunningMode = ...
  display_names_locale: Optional[str] = ...
  max_results: Optional[int] = ...
  score_threshold: Optional[float] = ...
  category_allowlist: Optional[List[str]] = ...
  category_denylist: Optional[List[str]] = ...
  result_callback: Optional[Callable[[ImageClassifierResult, image_lib.Image, int], None]] = ...


class ImageClassifier:
  """Class that performs image classification on images.

  The API expects a TFLite model with optional, but strongly recommended,
  TFLite Model Metadata.

  Input tensor:
    (kTfLiteUInt8/kTfLiteFloat32)
    - image input of size `[batch x height x width x channels]`.
    - batch inference is not supported (`batch` is required to be 1).
    - only RGB inputs are supported (`channels` is required to be 3).
    - if type is kTfLiteFloat32, NormalizationOptions are required to be
      attached to the metadata for input normalization.
  At least one output tensor with:
    (kTfLiteUInt8/kTfLiteFloat32)
    - `N `classes and either 2 or 4 dimensions, i.e. `[1 x N]` or
      `[1 x 1 x 1 x N]`
    - optional (but recommended) label map(s) as AssociatedFiles with type
      TENSOR_AXIS_LABELS, containing one label per line. The first such
      AssociatedFile (if any) is used to fill the `class_name` field of the
      results. The `display_name` field is filled from the AssociatedFile (if
      any) whose locale matches the `display_names_locale` field of the
      `ImageClassifierOptions` used at creation time ("en" by default, i.e.
      English). If none of these are available, only the `index` field of the
      results will be filled.
    - optional score calibration can be attached using ScoreCalibrationOptions
      and an AssociatedFile with type TENSOR_AXIS_SCORE_CALIBRATION. See
      metadata_schema.fbs [1] for more details.

  An example of such model can be found at:
  https://tfhub.dev/bohemian-visual-recognition-alliance/lite-model/models/mushroom-identification_v1/1

  [1]:
  https://github.com/google/mediapipe/blob/6cdc6443b6a7ed662744e2a2ce2d58d9c83e6d6f/mediapipe/tasks/metadata/metadata_schema.fbs#L456
  """
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  _dispatcher: _AsyncResultDispatcher
  _async_callback: _C_TYPES_RESULT_CALLBACK
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p, dispatcher: _AsyncResultDispatcher, async_callback: _C_TYPES_RESULT_CALLBACK) -> None:
    """Initializes the `ImageClassifier` object.

    Args:
      lib: The dispatch library to use for the image classifier.
      handle: The C pointer to the image classifier.
      dispatcher: The async result handler for the image classifier.
      async_callback: The c callback for the image classifier.
    """
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> ImageClassifier:
    """Creates an `ImageClassifier` object from a TensorFlow Lite model and the default `ImageClassifierOptions`.

    Note that the created `ImageClassifier` instance is in image mode, for
    classifying objects on single image inputs.

    Args:
      model_path: Path to the model.

    Returns:
      `ImageClassifier` object that's created from the model file and the
      default `ImageClassifierOptions`.

    Raises:
      ValueError: If failed to create `ImageClassifier` object from the provided
        file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: ImageClassifierOptions) -> ImageClassifier:
    """Creates the `ImageClassifier` object from image classifier options.

    Args:
      options: Options for the image classifier task.

    Returns:
      `ImageClassifier` object that's created from `options`.

    Raises:
      ValueError: If failed to create `ImageClassifier` object from
        `ImageClassifierOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def classify(self, image: image_lib.Image, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> ImageClassifierResult:
    """Performs image classification on the provided MediaPipe Image.

    Only use this method when the ImageClassifier is created with the image
    running mode.

    Args:
      image: MediaPipe Image.
      image_processing_options: Options for image processing.

    Returns:
      A classification result object that contains a list of classifications.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If image classification failed to run.
    """
    ...
  
  def classify_for_video(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> ImageClassifierResult:
    """Performs image classification on the provided video frames.

    Only use this method when the ImageClassifier is created with the video
    running mode. It's required to provide the video frame's timestamp (in
    milliseconds) along with the video frame. The input timestamps should be
    monotonically increasing for adjacent calls of this method.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input video frame in milliseconds.
      image_processing_options: Options for image processing.

    Returns:
      A classification result object that contains a list of classifications.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If image classification failed to run.
    """
    ...
  
  def classify_async(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> None:
    """Sends live image data (an Image with a unique timestamp) to perform image classification.

    Only use this method when the ImageClassifier is created with the live
    stream running mode. The input timestamps should be monotonically increasing
    for adjacent calls of this method. This method will return immediately after
    the input image is accepted. The results will be available via the
    `result_callback` provided in the `ImageClassifierOptions`. The
    `classify_async` method is designed to process live stream data such as
    camera input. To lower the overall latency, image classifier may drop the
    input images if needed. In other words, it's not guaranteed to have output
    per input image.

    The `result_callback` provides:
      - A classification result object that contains a list of classifications.
      - The input image that the image classifier runs on.
      - The input timestamp in milliseconds.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input image in milliseconds.
      image_processing_options: Options for image processing.

    Raises:
      ValueError: If the current input timestamp is smaller than what the image
        classifier has already processed.
    """
    ...
  
  def close(self): # -> None:
    """Closes ImageClassifier."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Closes ImageClassifier and exits the context manager.

    Args:
      exc_type: The exception type that caused the context manager to exit.
      exc_value: The exception value that caused the context manager to exit.
      traceback: The exception traceback that caused the context manager to
        exit.

    Raises:
      RuntimeError: If the MediaPipe Image Classifier task failed to
      close.
    """
    ...
  
  def __del__(self): # -> None:
    ...
  


