"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
import enum
from typing import List, Optional
from mediapipe.tasks.python.components.containers import keypoint as keypoint_module
from mediapipe.tasks.python.core import async_result_dispatcher, base_options as base_options_module, mediapipe_c_utils, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision import image_segmenter
from mediapipe.tasks.python.vision.core import image as image_module, image_processing_options as image_processing_options_module

"""MediaPipe interactive segmenter task."""
_BaseOptions = base_options_module.BaseOptions
_ImageProcessingOptions = image_processing_options_module.ImageProcessingOptions
_CFunction = mediapipe_c_utils.CFunction
_AsyncResultDispatcher = async_result_dispatcher.AsyncResultDispatcher
class MpRegionOfInterestC(ctypes.Structure):
  """The Region-Of-Interest (ROI) to interact with."""
  class Format(enum.IntEnum):
    UNSPECIFIED = ...
    KEYPOINT = ...
    SCRIBBLE = ...
  
  
  _fields_ = ...


class MpInteractiveSegmenterLegacyOptionsC(ctypes.Structure):
  """The MediaPipe Tasks MpInteractiveSegmenterLegacyOptions CTypes struct."""
  _fields_ = ...


_CTYPES_SIGNATURES = ...
@dataclasses.dataclass
class InteractiveSegmenterLegacyResult:
  """Output result of InteractiveSegmenterLegacy.

  confidence_masks: multiple masks of float image where, for each mask, each
  pixel represents the prediction confidence, usually in the [0, 1] range.

  category_mask: a category mask of uint8 image where each pixel represents the
  class which the pixel in the original image was predicted to belong to.
  """
  confidence_masks: Optional[List[image_module.Image]] = ...
  category_mask: Optional[image_module.Image] = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_result: image_segmenter.MpImageSegmenterResultC) -> InteractiveSegmenterLegacyResult:
    """Converts a C ImageSegmenterResult to a Python InteractiveSegmenterLegacyResult."""
    ...
  


@dataclasses.dataclass
class InteractiveSegmenterLegacyOptions:
  """Options for the interactive segmenter task.

  Attributes:
    base_options: Base options for the interactive segmenter task.
    running_mode: The running mode of the task.
    output_confidence_masks: Whether to output confidence masks.
    output_category_mask: Whether to output category mask.
    result_callback: The callback function that is invoked synchronously when
      the current thread is idle.
  """
  base_options: _BaseOptions
  output_confidence_masks: bool = ...
  output_category_mask: bool = ...
  @doc_controls.do_not_generate_docs
  def to_ctypes(self) -> MpInteractiveSegmenterLegacyOptionsC:
    """Generates an MpInteractiveSegmenterLegacyOptionsC ctypes struct."""
    ...
  


@dataclasses.dataclass
class RegionOfInterest:
  """The Region-Of-Interest (ROI) to interact with."""
  class Format(enum.Enum):
    UNSPECIFIED = ...
    KEYPOINT = ...
  
  
  format: Format
  keypoint: Optional[keypoint_module.NormalizedKeypoint] = ...
  @doc_controls.do_not_generate_docs
  def to_ctypes(self) -> MpRegionOfInterestC:
    """Converts a Python RegionOfInterest to a C MpRegionOfInterestC."""
    ...
  


class InteractiveSegmenterLegacy:
  """Class that performs interactive segmentation on images.

  Users can represent user interaction through `RegionOfInterest`, which gives
  a hint to InteractiveSegmenterLegacy to perform segmentation focusing on the
  given
  region of interest.

  The API expects a TFLite model with mandatory TFLite Model Metadata.

  Input tensor:
    (kTfLiteUInt8/kTfLiteFloat32)
    - image input of size `[batch x height x width x channels]`.
    - batch inference is not supported (`batch` is required to be 1).
    - RGB and greyscale inputs are supported (`channels` is required to be
      1 or 3).
    - if type is kTfLiteFloat32, NormalizationOptions are required to be
      attached to the metadata for input normalization.
  Output tensors:
    (kTfLiteUInt8/kTfLiteFloat32)
    - list of segmented masks.
    - if `output_type` is CATEGORY_MASK, uint8 Image, Image vector of size 1.
    - if `output_type` is CONFIDENCE_MASK, float32 Image list of size
      `channels`.
    - batch is always 1

  An example of such model can be found at:
  https://tfhub.dev/tensorflow/lite-model/deeplabv3/1/metadata/2
  """
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  _dispatcher: async_result_dispatcher.AsyncResultDispatcher
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p, dispatcher: async_result_dispatcher.AsyncResultDispatcher) -> None:
    """Initializes the `InteractiveSegmenterLegacy` object."""
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> InteractiveSegmenterLegacy:
    """Creates an `InteractiveSegmenterLegacy` object from a TensorFlow Lite model and the default `InteractiveSegmenterLegacyOptions`.

    Note that the created `InteractiveSegmenterLegacy` instance is in image
    mode, for
    performing image segmentation on single image inputs.

    Args:
      model_path: Path to the model.

    Returns:
      `InteractiveSegmenterLegacy` object that's created from the model file and
      the
      default `InteractiveSegmenterLegacyOptions`.

    Raises:
      ValueError: If failed to create `InteractiveSegmenterLegacy` object from
      the
        provided file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: InteractiveSegmenterLegacyOptions) -> InteractiveSegmenterLegacy:
    """Creates the `InteractiveSegmenterLegacy` object from interactive segmenter options.

    Args:
      options: Options for the interactive segmenter task.

    Returns:
      `InteractiveSegmenterLegacy` object that's created from `options`.

    Raises:
      ValueError: If failed to create `InteractiveSegmenterLegacy` object from
        `InteractiveSegmenterLegacyOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def segment(self, image: image_module.Image, roi: RegionOfInterest, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> InteractiveSegmenterLegacyResult:
    """Performs the actual segmentation task on the provided MediaPipe Image.

    The image can be of any size with format RGB.

    Args:
      image: MediaPipe Image.
      roi: Optional user-specified region of interest for segmentation.
      image_processing_options: Options for image processing.

    Returns:
      If the output_type is CATEGORY_MASK, the returned vector of images is
      per-category segmented image mask.
      If the output_type is CONFIDENCE_MASK, the returned vector of images
      contains only one confidence image mask. A segmentation result object that
      contains a list of segmentation masks as images.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If image segmentation failed to run.
    """
    ...
  
  def close(self): # -> None:
    """Closes the InteractiveSegmenterLegacy."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager."""
    ...
  
  def __del__(self): # -> None:
    ...
  


