"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
import enum
from typing import List
from mediapipe.tasks.python.core import base_options as base_options_module, mediapipe_c_utils, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image as image_module

"""MediaPipe interactive segmenter task."""
_BaseOptions = base_options_module.BaseOptions
_CStatusFunction = mediapipe_c_utils.CStatusFunction
class InteractiveSegmenterOptionsC(ctypes.Structure):
  """The MediaPipe Tasks InteractiveSegmenterOptions CTypes struct."""
  _fields_ = ...


class MpStrokePointC(ctypes.Structure):
  """The MediaPipe Tasks MpStrokePoint CTypes struct."""
  _fields_ = ...


class MpStrokeC(ctypes.Structure):
  """The MediaPipe Tasks MpStroke CTypes struct."""
  _fields_ = ...


class MpStrokesC(ctypes.Structure):
  """The MediaPipe Tasks MpStrokes CTypes struct."""
  _fields_ = ...


_CTYPES_SIGNATURES = ...
class BrushMode(enum.IntEnum):
  """The brush mode for interactive segmentation."""
  UNSPECIFIED = ...
  POSITIVE = ...
  NEGATIVE = ...
  LASSO = ...


@dataclasses.dataclass
class StrokePoint:
  """A single 2D point in a stroke.

  Attributes:
    x: The normalized x coordinate of the point.
    y: The normalized y coordinate of the point.
  """
  x: float
  y: float
  ...


@dataclasses.dataclass
class Stroke:
  """A stroke representing user interaction for segmentation.

  Attributes:
    brush_mode: The brush mode of the stroke.
    points: A list of points making up the stroke.
    is_completed: Whether the stroke is completed.
  """
  brush_mode: BrushMode
  points: List[StrokePoint]
  is_completed: bool
  ...


@dataclasses.dataclass
class InteractiveSegmenterOptions:
  """Options for the interactive segmenter task.

  Attributes:
    base_options: Base options for the interactive segmenter task.
  """
  base_options: _BaseOptions
  @doc_controls.do_not_generate_docs
  def to_ctypes(self) -> InteractiveSegmenterOptionsC:
    """Generates an InteractiveSegmenterOptionsC ctypes struct."""
    ...
  


class InteractiveSegmenter:
  """A task to perform interactive segmentation on images."""
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p) -> None:
    """Initializes the instance."""
    ...
  
  @classmethod
  def create_from_options(cls, options: InteractiveSegmenterOptions) -> InteractiveSegmenter:
    """Creates the `InteractiveSegmenter` object from `options`.

    Args:
      options: Options for the interactive segmenter task.

    Returns:
      `InteractiveSegmenter` object.
    """
    ...
  
  def set_image(self, image: image_module.Image) -> None:
    """Sets the image to be segmented."""
    ...
  
  def segment(self, strokes: List[Stroke]) -> image_module.Image:
    """Performs segmentation on the previously set image."""
    ...
  
  def close(self): # -> None:
    """Closes the InteractiveSegmenter."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager."""
    ...
  
  def __del__(self): # -> None:
    ...
  


