"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
import enum
from typing import Callable, Optional
from mediapipe.tasks.python.components.containers import landmark as landmark_lib
from mediapipe.tasks.python.core import async_result_dispatcher, base_options as base_options_lib, base_options_c as base_options_c_lib, serial_dispatcher
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image as image_lib, image_processing_options as image_processing_options_lib, vision_task_running_mode as running_mode_lib

"""MediaPipe pose landmarker task."""
_BaseOptions = base_options_lib.BaseOptions
_RunningMode = running_mode_lib.VisionTaskRunningMode
_ImageProcessingOptions = image_processing_options_lib.ImageProcessingOptions
_AsyncResultDispatcher = async_result_dispatcher.AsyncResultDispatcher
_LiveStreamPacket = async_result_dispatcher.LiveStreamPacket
class MpPoseLandmarkerResultC(ctypes.Structure):
  """The ctypes struct for MpPoseLandmarkerResult."""
  _fields_ = ...


_C_TYPES_RESULT_CALLBACK = ...
@dataclasses.dataclass
class PoseLandmarkerResult:
  """The pose landmarks detection result from PoseLandmarker, where each vector element represents a single pose detected in the image.

  Attributes:
    pose_landmarks: Detected pose landmarks in normalized image coordinates.
    pose_world_landmarks:  Detected pose landmarks in world coordinates.
    segmentation_masks: Optional segmentation masks for pose.
  """
  pose_landmarks: list[list[landmark_lib.NormalizedLandmark]]
  pose_world_landmarks: list[list[landmark_lib.Landmark]]
  segmentation_masks: Optional[list[image_lib.Image]] = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_struct: MpPoseLandmarkerResultC) -> PoseLandmarkerResult:
    """Creates a PoseLandmarkerResult from a ctypes struct."""
    ...
  


class PoseLandmark(enum.IntEnum):
  """The 33 pose landmarks."""
  NOSE = ...
  LEFT_EYE_INNER = ...
  LEFT_EYE = ...
  LEFT_EYE_OUTER = ...
  RIGHT_EYE_INNER = ...
  RIGHT_EYE = ...
  RIGHT_EYE_OUTER = ...
  LEFT_EAR = ...
  RIGHT_EAR = ...
  MOUTH_LEFT = ...
  MOUTH_RIGHT = ...
  LEFT_SHOULDER = ...
  RIGHT_SHOULDER = ...
  LEFT_ELBOW = ...
  RIGHT_ELBOW = ...
  LEFT_WRIST = ...
  RIGHT_WRIST = ...
  LEFT_PINKY = ...
  RIGHT_PINKY = ...
  LEFT_INDEX = ...
  RIGHT_INDEX = ...
  LEFT_THUMB = ...
  RIGHT_THUMB = ...
  LEFT_HIP = ...
  RIGHT_HIP = ...
  LEFT_KNEE = ...
  RIGHT_KNEE = ...
  LEFT_ANKLE = ...
  RIGHT_ANKLE = ...
  LEFT_HEEL = ...
  RIGHT_HEEL = ...
  LEFT_FOOT_INDEX = ...
  RIGHT_FOOT_INDEX = ...


class PoseLandmarksConnections:
  """The connections between pose landmarks."""
  @dataclasses.dataclass
  class Connection:
    """The connection class for pose landmarks."""
    start: int
    end: int
    ...
  
  
  POSE_LANDMARKS: list[Connection] = ...


class MpPoseLandmarkerOptionsC(ctypes.Structure):
  """The ctypes struct for MpPoseLandmarkerOptions."""
  _fields_ = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_c_options(cls, base_options: base_options_c_lib.MpBaseOptionsC, running_mode: _RunningMode, num_poses: int, min_pose_detection_confidence: float, min_pose_presence_confidence: float, min_tracking_confidence: float, output_segmentation_masks: bool, result_callback: _C_TYPES_RESULT_CALLBACK) -> MpPoseLandmarkerOptionsC:
    """Creates a MpPoseLandmarkerOptionsC object from the given options."""
    ...
  


@dataclasses.dataclass
class PoseLandmarkerOptions:
  """Options for the pose landmarker task.

  Attributes:
    base_options: Base options for the pose landmarker task.
    running_mode: The running mode of the task. Default to the image mode.
      PoseLandmarker has three running modes: 1) The image mode for detecting
      pose landmarks on single image inputs. 2) The video mode for detecting
      pose landmarks on the decoded frames of a video. 3) The live stream mode
      for detecting pose landmarks on the live stream of input data, such as
      from camera. In this mode, the "result_callback" below must be specified
      to receive the detection results asynchronously.
    num_poses: The maximum number of poses can be detected by the
      PoseLandmarker.
    min_pose_detection_confidence: The minimum confidence score for the pose
      detection to be considered successful.
    min_pose_presence_confidence: The minimum confidence score of pose presence
      score in the pose landmark detection.
    min_tracking_confidence: The minimum confidence score for the pose tracking
      to be considered successful.
    output_segmentation_masks: whether to output segmentation masks.
    result_callback: The user-defined result callback for processing live stream
      data. The result callback should only be specified when the running mode
      is set to the live stream mode.
  """
  base_options: _BaseOptions
  running_mode: _RunningMode = ...
  num_poses: int = ...
  min_pose_detection_confidence: float = ...
  min_pose_presence_confidence: float = ...
  min_tracking_confidence: float = ...
  output_segmentation_masks: bool = ...
  result_callback: Optional[Callable[[PoseLandmarkerResult, image_lib.Image, int], None]] = ...


_CTYPES_SIGNATURES = ...
class PoseLandmarker:
  """Class that performs pose landmarks detection on images."""
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  _dispatcher: _AsyncResultDispatcher
  _async_callback: _C_TYPES_RESULT_CALLBACK
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p, dispatcher: _AsyncResultDispatcher, async_callback: _C_TYPES_RESULT_CALLBACK) -> None:
    """Initializes the pose landmarker.

    Args:
      lib: The dispatch library to use for the pose landmarker.
      handle: The C pointer to the pose landmarker.
      dispatcher: The async result handler for the pose landmarker.
      async_callback: The c callback for the pose landmarker.
    """
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> PoseLandmarker:
    """Creates a `PoseLandmarker` object from a model bundle file and the default `PoseLandmarkerOptions`.

    Note that the created `PoseLandmarker` instance is in image mode, for
    detecting pose landmarks on single image inputs.

    Args:
      model_path: Path to the model.

    Returns:
      `PoseLandmarker` object that's created from the model file and the
      default `PoseLandmarkerOptions`.

    Raises:
      ValueError: If failed to create `PoseLandmarker` object from the
        provided file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: PoseLandmarkerOptions) -> PoseLandmarker:
    """Creates the `PoseLandmarker` object from pose landmarker options.

    Args:
      options: Options for the pose landmarker task.

    Returns:
      `PoseLandmarker` object that's created from `options`.

    Raises:
      ValueError: If failed to create `PoseLandmarker` object from
        `PoseLandmarkerOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def detect(self, image: image_lib.Image, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> PoseLandmarkerResult:
    """Performs pose landmarks detection on the given image.

    Only use this method when the PoseLandmarker is created with the image
    running mode.

    Args:
      image: MediaPipe Image.
      image_processing_options: Options for image processing.

    Returns:
      The pose landmarker detection results.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If pose landmarker detection failed to run.
    """
    ...
  
  def detect_for_video(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> PoseLandmarkerResult:
    """Performs pose landmarks detection on the provided video frame.

    Only use this method when the PoseLandmarker is created with the video
    running mode.

    Only use this method when the PoseLandmarker is created with the video
    running mode. It's required to provide the video frame's timestamp (in
    milliseconds) along with the video frame. The input timestamps should be
    monotonically increasing for adjacent calls of this method.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input video frame in milliseconds.
      image_processing_options: Options for image processing.

    Returns:
      The pose landmarker detection results.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If pose landmarker detection failed to run.
    """
    ...
  
  def detect_async(self, image: image_lib.Image, timestamp_ms: int, image_processing_options: Optional[_ImageProcessingOptions] = ...) -> None:
    """Sends live image data to perform pose landmarks detection.

    The results will be available via the "result_callback" provided in the
    PoseLandmarkerOptions. Only use this method when the PoseLandmarker is
    created with the live stream running mode.

    Only use this method when the PoseLandmarker is created with the live
    stream running mode. The input timestamps should be monotonically increasing
    for adjacent calls of this method. This method will return immediately after
    the input image is accepted. The results will be available via the
    `result_callback` provided in the `PoseLandmarkerOptions`. The
    `detect_async` method is designed to process live stream data such as
    camera input. To lower the overall latency, pose landmarker may drop the
    input images if needed. In other words, it's not guaranteed to have output
    per input image.

    The `result_callback` provides:
      - The pose landmarker detection results.
      - The input image that the pose landmarker runs on.
      - The input timestamp in milliseconds.

    Args:
      image: MediaPipe Image.
      timestamp_ms: The timestamp of the input image in milliseconds.
      image_processing_options: Options for image processing.

    Raises:
      ValueError: If the current input timestamp is smaller than what the
      pose landmarker has already processed.
    """
    ...
  
  def close(self): # -> None:
    """Closes the PoseLandmarker."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, exc_type, exc_value, traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager.

    Args:
      exc_type: The exception type that caused the context manager to exit.
      exc_value: The exception value that caused the context manager to exit.
      traceback: The exception traceback that caused the context manager to
        exit.

    Raises:
      RuntimeError: If the MediaPipe PoseLandmarker task failed to close.
    """
    ...
  
  def __del__(self): # -> None:
    ...
  


