"""
This type stub file was generated by pyright.
"""

import numpy as np

"""A module to record audio in a streaming basis."""
class AudioRecord:
  """A class to record audio in a streaming basis."""
  def __init__(self, channels: int, sampling_rate: int, buffer_size: int) -> None:
    """Creates an AudioRecord instance.

    Args:
      channels: Number of input channels.
      sampling_rate: Sampling rate in Hertz.
      buffer_size: Size of the ring buffer in number of samples.

    Raises:
      ValueError: if any of the arguments is non-positive.
      ImportError: if failed to import `sounddevice`.
      OSError: if failed to load `PortAudio`.
    """
    ...
  
  @property
  def channels(self) -> int:
    ...
  
  @property
  def sampling_rate(self) -> int:
    ...
  
  @property
  def buffer_size(self) -> int:
    ...
  
  def start_recording(self) -> None:
    """Starts the audio recording."""
    ...
  
  def stop(self) -> None:
    """Stops the audio recording."""
    ...
  
  def read(self, size: int) -> np.ndarray:
    """Reads the latest audio data captured in the buffer.

    Args:
      size: Number of samples to read from the buffer.

    Returns:
      A NumPy array containing the audio data.

    Raises:
      ValueError: Raised if `size` is larger than the buffer size.
    """
    ...
  


