"""
This type stub file was generated by pyright.
"""

import enum
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""The running mode of MediaPipe Audio Tasks."""
_CTYPE_VALUE_MAP = ...
class AudioTaskRunningMode(enum.Enum):
  """MediaPipe audio task running mode.

  Attributes:
    AUDIO_CLIPS: The mode for running a mediapipe audio task on independent
      audio clips.
    AUDIO_STREAM: The mode for running a mediapipe audio task on an audio
      stream, such as from microphone.
  """
  AUDIO_CLIPS = ...
  AUDIO_STREAM = ...
  @property
  @doc_controls.do_not_generate_docs
  def ctype(self) -> int:
    """Generates a C API int object."""
    ...
  


