"""
This type stub file was generated by pyright.
"""

import mediapipe.tasks.python.components.processors.classifier_options

"""MediaPipe Tasks Components Processors API."""
ClassifierOptions = ...
