"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, List, Optional

"""Classifier options data class."""
@dataclasses.dataclass
class ClassifierOptions:
  """Options for classification processor.

  Attributes:
    display_names_locale: The locale to use for display names specified through
      the TFLite Model Metadata.
    max_results: The maximum number of top-scored classification results to
      return.
    score_threshold: Overrides the ones provided in the model metadata. Results
      below this value are rejected.
    category_allowlist: Allowlist of category names. If non-empty, detection
      results whose category name is not in this set will be filtered out.
      Duplicate or unknown category names are ignored. Mutually exclusive with
      `category_denylist`.
    category_denylist: Denylist of category names. If non-empty, detection
      results whose category name is in this set will be filtered out. Duplicate
      or unknown category names are ignored. Mutually exclusive with
      `category_allowlist`.
  """
  display_names_locale: Optional[str] = ...
  max_results: Optional[int] = ...
  score_threshold: Optional[float] = ...
  category_allowlist: Optional[List[str]] = ...
  category_denylist: Optional[List[str]] = ...
  def __eq__(self, other: Any) -> bool:
    """Checks if this object is equal to the given object.

    Args:
      other: The object to be compared with.

    Returns:
      True if the objects are equal.
    """
    ...
  


