"""
This type stub file was generated by pyright.
"""

import ctypes
import mediapipe.tasks.python.components.processors.classifier_options as classifier_options_module

"""C types for MpClassifierOptions."""
class MpClassifierOptionsC(ctypes.Structure):
  _fields_ = ...


def convert_to_classifier_options_c(src: classifier_options_module.ClassifierOptions) -> MpClassifierOptionsC:
  """Converts a Python ClassifierOptions object to a MpClassifierOptionsC object."""
  ...

