"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
from typing import List, Optional
from mediapipe.tasks.python.core import base_options as base_options_module, serial_dispatcher

"""MediaPipe language detector task."""
_BaseOptions = base_options_module.BaseOptions
Category = ...
Classifications = ...
ClassifierOptions = ...
@dataclasses.dataclass
class LanguageDetectorResult:
  @dataclasses.dataclass
  class Detection:
    """A language code and its probability."""
    language_code: str
    probability: float
    ...
  
  
  detections: List[Detection]


class MpLanguageDetectorPredictionC(ctypes.Structure):
  """A language code and its probability."""
  _fields_ = ...


class MpLanguageDetectorResultC(ctypes.Structure):
  """Language detector output."""
  _fields_ = ...


class MpLanguageDetectorOptionsC(ctypes.Structure):
  _fields_ = ...


@dataclasses.dataclass
class LanguageDetectorOptions:
  """Options for the language detector task.

  Attributes:
    base_options: Base options for the language detector task.
    display_names_locale: The locale to use for display names specified through
      the TFLite Model Metadata.
    max_results: The maximum number of top-scored classification results to
      return.
    score_threshold: Overrides the ones provided in the model metadata. Results
      below this value are rejected.
    category_allowlist: Allowlist of category names. If non-empty,
      classification results whose category name is not in this set will be
      filtered out. Duplicate or unknown category names are ignored. Mutually
      exclusive with `category_denylist`.
    category_denylist: Denylist of category names. If non-empty, classification
      results whose category name is in this set will be filtered out. Duplicate
      or unknown category names are ignored. Mutually exclusive with
      `category_allowlist`.
  """
  base_options: _BaseOptions
  display_names_locale: Optional[str] = ...
  max_results: Optional[int] = ...
  score_threshold: Optional[float] = ...
  category_allowlist: Optional[List[str]] = ...
  category_denylist: Optional[List[str]] = ...
  def to_ctypes(self) -> MpLanguageDetectorOptionsC:
    """Generates a ctypes MpLanguageDetectorOptionsC."""
    ...
  


_CTYPES_SIGNATURES = ...
class LanguageDetector:
  """Class that predicts the language of an input text.

  This API expects a TFLite model with TFLite Model Metadata that contains the
  mandatory (described below) input tensors, output tensor, and the language
  codes in an AssociatedFile.

  Input tensors:
    (kTfLiteString)
    - 1 input tensor that is scalar or has shape [1] containing the input
      string.
  Output tensor:
    (kTfLiteFloat32)
    - 1 output tensor of shape`[1 x N]` where `N` is the number of languages.
  """
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p) -> None:
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> LanguageDetector:
    """Creates an `LanguageDetector` object from a TensorFlow Lite model and the default `LanguageDetectorOptions`.

    Args:
      model_path: Path to the model.

    Returns:
      `LanguageDetector` object that's created from the model file and the
      default `LanguageDetectorOptions`.

    Raises:
      ValueError: If failed to create `LanguageDetector` object from the
      provided
        file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: LanguageDetectorOptions) -> LanguageDetector:
    """Creates the `LanguageDetector` object from language detector options.

    Args:
      options: Options for the language detector task.

    Returns:
      `LanguageDetector` object that's created from `options`.

    Raises:
      ValueError: If failed to create `LanguageDetector` object from
        `LanguageDetectorOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def detect(self, text: str) -> LanguageDetectorResult:
    """Predicts the language of the input `text`.

    Args:
      text: The input text.

    Returns:
      A `LanguageDetectorResult` object that contains a list of languages and
      scores.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If language detection failed to run.
    """
    ...
  
  def close(self): # -> None:
    """Shuts down the MediaPipe task instance."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, unused_exc_type, unused_exc_value, unused_traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager.

    Raises:
      RuntimeError: If the MediaPipe LanguageDetector task failed to close.
    """
    ...
  
  def __del__(self): # -> None:
    ...
  


