"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
import enum
from typing import Callable, List, Optional, Union
from mediapipe.tasks.python.core import base_options as base_options_module, serial_dispatcher

"""MediaPipe text proofreader task."""
class _MpTextProofreaderOptionsC(ctypes.Structure):
  _fields_ = ...


@dataclasses.dataclass
class TextProofreaderOptions:
  """Options for the text proofreader task.

  Attributes:
    base_options: Base options for the text proofreader task.
    max_num_tokens: The maximum number of tokens for proofreader tasks. If set,
      the proofread output text will be truncated if the input and output exceed
      this value. If not set, then the default max_num_tokens is roughly 8k
      tokens due to the model's capacity.
  """
  base_options: base_options_module.BaseOptions
  max_num_tokens: Optional[int] = ...
  def to_ctypes(self) -> _MpTextProofreaderOptionsC:
    """Generates a ctypes TextProofreaderOptionsC."""
    ...
  


class CorrectionType(enum.Enum):
  """The type of correction."""
  SAME = ...
  INSERTION = ...
  DELETION = ...


class _MpCorrectionC(ctypes.Structure):
  _fields_ = ...


class _MpTextProofreaderResultC(ctypes.Structure):
  _fields_ = ...


class _MpTextProofreaderStreamResultC(ctypes.Structure):
  _fields_ = ...


@dataclasses.dataclass
class Correction:
  """A single correction.

  Attributes:
    type: The type of correction.
    text: The text associated with the correction.
  """
  type: CorrectionType
  text: str
  ...


@dataclasses.dataclass
class TextProofreaderResult:
  """Result of the text proofreader task.

  Attributes:
    proofread_text: The proofread text with corrections applied.
    corrections: List of unchanged, deleted, and inserted text segments.
    done: Whether the proofreading is done.
  """
  proofread_text: Optional[str]
  corrections: List[Correction]
  done: bool
  @classmethod
  def create_from_ctypes(cls, c_result: Union[_MpTextProofreaderResultC, _MpTextProofreaderStreamResultC]) -> TextProofreaderResult:
    """Creates a `TextProofreaderResult` object from a C struct."""
    ...
  


_ProofreaderCallback = ...
_CTYPES_SIGNATURES = ...
class TextProofreader:
  """Performs proofreading on text."""
  _lib: serial_dispatcher.SerialDispatcher
  _proofreader_handle: ctypes.c_void_p
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p) -> None:
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> TextProofreader:
    """Creates a `TextProofreader` object from model path.

    Args:
      model_path: Path to the model.

    Returns:
      `TextProofreader` object that's created from the model file and the
      default `TextProofreaderOptions`.

    Raises:
      ValueError: If failed to create `TextProofreader` object from the provided
        file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: TextProofreaderOptions) -> TextProofreader:
    """Creates the `TextProofreader` object from text proofreader options.

    Args:
      options: Options for the text proofreader task.

    Returns:
      `TextProofreader` object that's created from `options`.

    Raises:
      ValueError: If failed to create `TextProofreader` object from
        `TextProofreaderOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def proofread(self, text: str) -> TextProofreaderResult:
    """Performs proofreading on the input `text`.

    Args:
      text: The input text.

    Returns:
      A `TextProofreaderResult` object that contains the proofread text.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If proofreading failed to run.
    """
    ...
  
  def proofread_async(self, text: str, result_callback: Callable[[Optional[TextProofreaderResult], Optional[str]], None]) -> None:
    """Performs proofreading on the input `text` asynchronously.

    Args:
      text: The input text.
      result_callback: A callback function that will be called with the
        TextProofreaderResult and an error message (if any).

    Raises:
      ValueError: If any of the input arguments is invalid, or if
        proofread_async is called before the previous call has finished.
      RuntimeError: If proofreading failed to run.
    """
    ...
  
  def close(self): # -> None:
    """Shuts down the MediaPipe task instance."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, unused_exc_type, unused_exc_value, unused_traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager."""
    ...
  
  def __del__(self): # -> None:
    ...
  


