"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
import enum
from typing import Callable, Optional
from mediapipe.tasks.python.core import base_options as base_options_module, serial_dispatcher

"""MediaPipe text summarizer task."""
class Mode(enum.IntEnum):
  """The mode of the text summarizer."""
  TLDR = ...
  KEYPOINTS = ...


class _MpTextSummarizerOptionsC(ctypes.Structure):
  _fields_ = ...


@dataclasses.dataclass
class TextSummarizerOptions:
  """Options for the text summarizer task.

  Attributes:
    base_options: Base options for the text summarizer task.
    mode: The mode of the text summarizer task.
    max_num_tokens: The maximum number of tokens for summarization tasks. If
      set, the summarization will be truncated if the input and output exceed
      this value. If not set, then the default max_num_tokens is roughly 8k
      tokens due to the model's capacity.
  """
  base_options: base_options_module.BaseOptions
  mode: Mode = ...
  max_num_tokens: Optional[int] = ...
  def to_ctypes(self) -> _MpTextSummarizerOptionsC:
    """Generates a ctypes TextSummarizerOptionsC."""
    ...
  


class _MpTextSummarizerResultC(ctypes.Structure):
  _fields_ = ...


class _MpTextSummarizerStreamResultC(ctypes.Structure):
  _fields_ = ...


@dataclasses.dataclass
class TextSummarizerResult:
  """Result of the text summarizer task.

  Attributes:
    summary: The generated summary text.
    done: Whether the summarization is done.
  """
  summary: Optional[str]
  done: bool
  ...


_SummarizerCallback = ...
_CTYPES_SIGNATURES = ...
class TextSummarizer:
  """Performs summarization on text."""
  _lib: serial_dispatcher.SerialDispatcher
  _summarizer_handle: ctypes.c_void_p
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p) -> None:
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> TextSummarizer:
    """Creates a `TextSummarizer` object from model path.

    Args:
      model_path: Path to the model.

    Returns:
      `TextSummarizer` object that's created from the model file and the
      default `TextSummarizerOptions`.

    Raises:
      ValueError: If failed to create `TextSummarizer` object from the provided
        file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: TextSummarizerOptions) -> TextSummarizer:
    """Creates the `TextSummarizer` object from text summarizer options.

    Args:
      options: Options for the text summarizer task.

    Returns:
      `TextSummarizer` object that's created from `options`.

    Raises:
      ValueError: If failed to create `TextSummarizer` object from
        `TextSummarizerOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def summarize(self, text: str) -> TextSummarizerResult:
    """Performs summarization on the input `text`.

    Args:
      text: The input text.

    Returns:
      A `TextSummarizerResult` object that contains the summary.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If text summarization failed to run.
    """
    ...
  
  def summarize_async(self, text: str, result_callback: Callable[[Optional[TextSummarizerResult], Optional[str]], None]) -> None:
    """Performs summarization on the input `text` asynchronously.

    Args:
      text: The input text.
      result_callback: A callback function that will be called with the
        TextSummarizerResult and an error message (if any). The callback
        signature is `(result: Optional[TextSummarizerResult], error:
        Optional[str]) -> None`.

    Raises:
      ValueError: If any of the input arguments is invalid, or if
        summarize_async is called before the previous call has finished.
      RuntimeError: If text summarization failed to run.
    """
    ...
  
  def close(self): # -> None:
    """Shuts down the MediaPipe task instance."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, unused_exc_type, unused_exc_value, unused_traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager."""
    ...
  
  def __del__(self): # -> None:
    ...
  


