"""
This type stub file was generated by pyright.
"""

import ctypes
import dataclasses
import enum
from typing import Optional
from mediapipe.tasks.python.components.containers import embedding_result as embedding_result_module
from mediapipe.tasks.python.core import base_options as base_options_module, serial_dispatcher

"""MediaPipe text embedder task."""
TextEmbedderResult = ...
class EmbeddingType(enum.Enum):
  """The embedding type of Gecko embeddings."""
  RETRIEVAL_QUERY = ...
  RETRIEVAL_DOCUMENT = ...
  SEMANTIC_SIMILARITY = ...
  CLASSIFICATION = ...
  CLUSTERING = ...
  QUESTION_ANSWERING = ...
  FACT_CHECKING = ...
  CODE_RETRIEVAL = ...


class TextRole(enum.Enum):
  """The role of the text in the context of the embedding task."""
  QUERY = ...
  DOCUMENT = ...


class _MpTextFormatContextC(ctypes.Structure):
  """C struct for MpTextFormatContext."""
  _fields_ = ...


@dataclasses.dataclass
class TextFormatContext:
  """Formatting options for Gecko embeddings.

  Attributes:
    task_type: The embedding type.
    title: The title of the text.
    role: The role of the text.
  """
  task_type: EmbeddingType
  title: Optional[str] = ...
  role: TextRole = ...
  def to_ctypes(self) -> _MpTextFormatContextC:
    """Generates a ctypes _MpTextFormatContextC object."""
    ...
  


class _MpEmbedderOptionsC(ctypes.Structure):
  """C struct for MpEmbedderOptions."""
  _fields_ = ...


class _MpTextEmbedderOptionsC(ctypes.Structure):
  """C struct for MpTextEmbedderOptions."""
  _fields_ = ...


_CTYPES_SIGNATURES = ...
@dataclasses.dataclass
class TextEmbedderOptions:
  """Options for the text embedder task.

  Attributes:
    base_options: Base options for the text embedder task.
    l2_normalize: Whether to normalize the returned feature vector with L2 norm.
      Use this option only if the model does not already contain a native
      L2_NORMALIZATION TF Lite Op. In most cases, this is already the case and
      L2 norm is thus achieved through TF Lite inference.
    quantize: Whether the returned embedding should be quantized to bytes via
      scalar quantization. Embeddings are implicitly assumed to be unit-norm and
      therefore any dimension is guaranteed to have a value in [-1.0, 1.0]. Use
      the l2_normalize option if this is not the case.
  """
  base_options: base_options_module.BaseOptions
  l2_normalize: Optional[bool] = ...
  quantize: Optional[bool] = ...
  def to_ctypes(self) -> _MpTextEmbedderOptionsC:
    """Generates a ctypes MpTextEmbedderOptionsC object."""
    ...
  


class TextEmbedder:
  """Class that performs embedding extraction on text.

  This API expects a TFLite model with TFLite Model Metadata that contains the
  mandatory (described below) input tensors and output tensors. Metadata should
  contain the input process unit for the model's Tokenizer as well as input /
  output tensor metadata.

  Input tensors:
    (kTfLiteInt32)
    - 3 input tensors of size `[batch_size x bert_max_seq_len]` with names
      "ids", "mask", and "segment_ids" representing the input ids, mask ids, and
      segment ids respectively.
    - or 1 input tensor of size `[batch_size x max_seq_len]` representing the
      input ids.

  At least one output tensor with:
    (kTfLiteFloat32)
    - `N` components corresponding to the `N` dimensions of the returned
      feature vector for this output layer.
    - Either 2 or 4 dimensions, i.e. `[1 x N]` or `[1 x 1 x 1 x N]`.
  """
  _lib: serial_dispatcher.SerialDispatcher
  _handle: ctypes.c_void_p
  def __init__(self, lib: serial_dispatcher.SerialDispatcher, handle: ctypes.c_void_p) -> None:
    ...
  
  @classmethod
  def create_from_model_path(cls, model_path: str) -> TextEmbedder:
    """Creates an `TextEmbedder` object from a TensorFlow Lite model and the default `TextEmbedderOptions`.

    Args:
      model_path: Path to the model.

    Returns:
      `TextEmbedder` object that's created from the model file and the default
      `TextEmbedderOptions`.

    Raises:
      ValueError: If failed to create `TextEmbedder` object from the provided
        file such as invalid file path.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  @classmethod
  def create_from_options(cls, options: TextEmbedderOptions) -> TextEmbedder:
    """Creates the `TextEmbedder` object from text embedder options.

    Args:
      options: Options for the text embedder task.

    Returns:
      `TextEmbedder` object that's created from `options`.

    Raises:
      ValueError: If failed to create `TextEmbedder` object from
        `TextEmbedderOptions` such as missing the model.
      RuntimeError: If other types of error occurred.
    """
    ...
  
  def embed(self, text: str, format_context: Optional[TextFormatContext] = ...) -> embedding_result_module.EmbeddingResult:
    """Performs text embedding extraction on the provided text.

    Args:
      text: The input text.
      format_context: Optional formatting options for models that require prompt
        formatting, such as the family of Gecko models.

    Returns:
      An embedding result object that contains a list of embeddings.

    Raises:
      ValueError: If any of the input arguments is invalid.
      RuntimeError: If text embedder failed to run.
    """
    ...
  
  @classmethod
  def cosine_similarity(cls, u: embedding_result_module.Embedding, v: embedding_result_module.Embedding) -> float:
    """Utility function to compute cosine similarity between two embedding entries.

    May return an InvalidArgumentError if e.g. the feature vectors are
    of different types (quantized vs. float), have different sizes, or have a
    an L2-norm of 0.

    Args:
      u: An embedding entry.
      v: An embedding entry.

    Returns:
      The cosine similarity for the two embeddings.

    Raises:
      ValueError: May return an error if e.g. the feature vectors are of
        different types (quantized vs. float), have different sizes, or have
        an L2-norm of 0.
    """
    ...
  
  def close(self): # -> None:
    """Shuts down the MediaPipe task instance."""
    ...
  
  def __enter__(self): # -> Self:
    """Returns `self` upon entering the runtime context."""
    ...
  
  def __exit__(self, unused_exc_type, unused_exc_value, unused_traceback): # -> None:
    """Shuts down the MediaPipe task instance on exit of the context manager."""
    ...
  
  def __del__(self): # -> None:
    ...
  


