"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Optional
from mediapipe.tasks.python.components.containers import rect as rect_module
from mediapipe.tasks.python.core.optional_dependencies import doc_controls
from mediapipe.tasks.python.vision.core import image_processing_options_c as image_processing_options_c_module

"""MediaPipe vision options for image processing."""
@dataclasses.dataclass
class ImageProcessingOptions:
  """Options for image processing.

  If both region-of-interest and rotation are specified, the crop around the
  region-of-interest is extracted first, then the specified rotation is applied
   to the crop.

  Attributes:
    region_of_interest: The optional region-of-interest to crop from the image.
      If not specified, the full image is used. Coordinates must be in [0,1]
      with 'left' < 'right' and 'top' < 'bottom'.
    rotation_degrees: The rotation to apply to the image (or cropped
      region-of-interest), in degrees clockwise. The rotation must be a multiple
      (positive or negative) of 90°.
  """
  region_of_interest: Optional[rect_module.RectF] = ...
  rotation_degrees: int = ...
  @doc_controls.do_not_generate_docs
  def to_ctypes(self) -> image_processing_options_c_module.MpImageProcessingOptionsC:
    """Generates a MpImageProcessingOptionsC object."""
    ...
  


