"""
This type stub file was generated by pyright.
"""

import ctypes

"""MediaPipe ImageProcessingOptions C API types."""
class MpImageProcessingOptionsC(ctypes.Structure):
  """CTypes for ImageProcessingOptions."""
  _fields_ = ...


