"""
This type stub file was generated by pyright.
"""

import ctypes
import enum
import numpy as np
from typing import Any
from mediapipe.tasks.python.core import mediapipe_c_utils
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""MediaPipe image container."""
_CFunction = mediapipe_c_utils.CFunction
_CStatusFunction = mediapipe_c_utils.CStatusFunction
class ImageFormat(enum.IntEnum):
  """An enum describing supported raw image formats.

  SRGB: sRGB, interleaved: one byte for R, then one byte for G, then one byte
    for B for each pixel.

  SRGBA: sRGBA, interleaved: one byte for R, one byte for G, one byte for B, one
    byte for alpha or unused.

  SBGRA: sBGRA, interleaved: one byte for B, one byte for G, one byte for R, one
    byte for alpha or unused.

  GRAY8: Grayscale, one byte per pixel.

  GRAY16: Grayscale, one uint16 per pixel.

  SRGB48: sRGB, interleaved, each component is a uint16.

  SRGBA64: sRGBA, interleaved, each component is a uint16.

  VEC32F1: One float per pixel.

  VEC32F2: Two floats per pixel.
  """
  UNKNOWN = ...
  SRGB = ...
  SRGBA = ...
  GRAY8 = ...
  GRAY16 = ...
  SRGB48 = ...
  SRGBA64 = ...
  VEC32F1 = ...
  VEC32F2 = ...
  VEC32F4 = ...


_CTYPES_SIGNATURES = ...
class Image:
  """A container for storing an image or a video frame.

  Formats supported by Image are listed in the ImageFormat enum.
  Pixels are encoded row-major in an interleaved fashion. Image supports
  uint8, uint16, and float as its data types.

  Image can be created by copying the data from a numpy ndarray that stores
  the pixel data continuously. The data in an Image will become immutable
  after creation.

  The pixel data in an Image can be retrieved as a numpy ndarray by calling
  `Image.numpy_view()`. The returned numpy ndarray is a reference to the
  internal data and itself is unwritable. If the callers want to modify the
  numpy ndarray, it's required to obtain a copy of it.

  Pixel data retrieval examples:

  ```python
  for channel in range(num_channel):
    for col in range(width):
      for row in range(height):
        print(image[row, col, channel])

  output_ndarray = image.numpy_view()
  print(output_ndarray[0, 0, 0])
  copied_ndarray = np.copy(output_ndarray)
  copied_ndarray[0,0,0] = 0
  ```
  """
  _lib: ctypes.CDLL
  _image_ptr: ctypes.c_void_p
  def __init__(self, image_format: ImageFormat, data: np.ndarray) -> None:
    """Creates an Image object from a numpy ndarray.

    For uint8 data type, valid ImageFormat are GRAY8, SRGB, and SRGBA.
    For uint16 data type, valid ImageFormat are GRAY16, SRGB48, and SRGBA64.
    For float32 data type, valid ImageFormat are VEC32F1, VEC32F2, and VEC32F4.

    Args:
      image_format: The format of the image data.
      data: A numpy ndarray containing the image data.
    """
    ...
  
  @classmethod
  def create_from_file(cls, file_name: str) -> Image:
    """Creates an `Image` object from an image file.

    Args:
      file_name: The path to the image file.

    Returns:
      An `Image` object.

    Raises:
      RuntimeError: If the image file cannot be decoded.
    """
    ...
  
  @classmethod
  @doc_controls.do_not_generate_docs
  def create_from_ctypes(cls, image_ptr: ctypes.c_void_p) -> Image:
    """Creates an `Image` object from a ctypes pointer.

    This methods creates a copy of the Image object, which points to the same
    underlying image data and extends its lifetime until the returned object
    gets garbage collected. If the original image is on GPU, the copy will
    allocate the pixel data on the CPU.

    Args:
      image_ptr: A ctypes pointer to the image data.

    Returns:
      An `Image` object.
    """
    ...
  
  @classmethod
  @doc_controls.do_not_generate_docs
  def free_ctypes(cls, image_ptr: ctypes.c_void_p) -> None:
    """Frees a ctypes pointer to an image.

    Args:
      image_ptr: A ctypes pointer to the image data.
    """
    ...
  
  def numpy_view(self) -> np.ndarray:
    """Returns the image pixel data as an unwritable numpy ndarray.

    Realign the pixel data to be stored contiguously and return a reference to
    the unwritable numpy ndarray. If the callers want to modify the numpy array
    data, it's required to obtain a copy of the ndarray.

    Returns:
      An unwritable numpy ndarray.

    Examples:
      ```
      output_ndarray = image.numpy_view()
      copied_ndarray = np.copy(output_ndarray)
      copied_ndarray[0,0,0] = 0
      ```
    """
    ...
  
  def __getitem__(self, key: tuple[int, ...]) -> Any:
    """Use the indexer operators to access pixel data.

    Args:
      key: A tuple of integers representing the row, column, and channel indices
        (or row and column for single channel images).

    Returns:
      The pixel data at the specified index.

    Raises:
      IndexError: If the index is invalid or out of bounds.

    Examples:
      ```
      for channel in range(num_channel):
        for col in range(width):
          for row in range(height):
            print(image[row, col, channel])
    ```
    """
    ...
  
  def uses_gpu(self) -> bool:
    """Return True if data is currently on the GPU.."""
    ...
  
  def is_contiguous(self) -> bool:
    """Return True if the pixel data is stored contiguously (without any alignment padding areas)."""
    ...
  
  def is_empty(self) -> bool:
    """Return True if the pixel data is unallocated."""
    ...
  
  def is_aligned(self, alignment_boundary: int) -> bool:
    """Return True if each row of the data is aligned to alignment boundary, which must be 1 or a power of 2.

    Args:
      alignment_boundary: An integer.

    Returns:
      A boolean.

    Examples:
      ```
      image.is_aligned(16)
      ```
    """
    ...
  
  @property
  def step(self) -> int:
    """Returns the width step of the image."""
    ...
  
  @property
  def width(self) -> int:
    """Returns the width of the image."""
    ...
  
  @property
  def height(self) -> int:
    """Returns the height of the image."""
    ...
  
  @property
  def channels(self) -> int:
    """Returns the number of channels in the image."""
    ...
  
  @property
  def image_format(self) -> ImageFormat:
    """Returns the image format."""
    ...
  
  def __del__(self): # -> None:
    """Frees the internal C Image object."""
    ...
  


