"""
This type stub file was generated by pyright.
"""

import enum
from typing import Any, Callable, Mapping, Optional
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""The running mode of MediaPipe Vision Tasks."""
_CTYPE_VALUE_MAP = ...
class VisionTaskRunningMode(enum.Enum):
  """MediaPipe vision task running mode.

  Attributes:
    IMAGE: The mode for running a mediapipe vision task on single image inputs.
    VIDEO: The mode for running a mediapipe vision task on the decoded frames
      of an input video.
    LIVE_STREAM: The mode for running a mediapipe vision task on a live stream
      of input data, such as from camera.
  """
  IMAGE = ...
  VIDEO = ...
  LIVE_STREAM = ...
  @property
  @doc_controls.do_not_generate_docs
  def ctype(self) -> int:
    """Generates a C API int object."""
    ...
  


def validate_running_mode(running_mode: VisionTaskRunningMode, packet_callback: Optional[Callable[[Mapping[str, Any]], None]] = ...) -> None:
  """Validates the running mode of the mediapipe vision task.

  Args:
    running_mode: The running mode of the mediapipe vision task.
    packet_callback: The user-defined result callback.

  Raises:
    ValueError: If packet callback is provided in image or video mode or
    missing in live stream mode.
  """
  ...

