"""
This type stub file was generated by pyright.
"""

import ctypes

"""C types for MpBaseOptions."""
class MpBaseOptionsC(ctypes.Structure):
  """C types for MpBaseOptions.

  Attributes:
    model_asset_buffer: `bytes`, the model asset buffer.
    model_asset_buffer_count: `int`, the size of the model asset buffer.
    model_asset_path: `bytes`, the path to the model asset.
    file_descriptor: `int`, the file descriptor of the model asset.
    delegate: `int`, the delegate to use.
    host_environment: `int`, the environment in which the task is running.
    host_system: `int`, the system on which the task is running.
    host_version: `bytes`, the Python version as a UTF-8 string.
    ca_bundle_path: `bytes`, the path to the CA bundle file as a UTF-8 string.
    app_id: `bytes`, optional application id as a UTF-8 string.
    app_version: `bytes`, optional application version as a UTF-8 string.
  """
  _fields_ = ...


