"""
This type stub file was generated by pyright.
"""

import dataclasses
import enum
from typing import Any, Optional
from mediapipe.tasks.python.core import base_options_c as base_options_c_lib
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""Base options for MediaPipe Task APIs."""
HOST_ENVIRONMENT_PYTHON: int = ...
class _HostSystem(enum.IntEnum):
  """An mapping for the C enum values for the host operating system.

  Attributes:
    HOST_SYSTEM_UNKNOWN: Unknown host system.
    HOST_SYSTEM_LINUX: Linux host system.
    HOST_SYSTEM_MAC: MacOS host system.
    HOST_SYSTEM_WINDOWS: Windows host system.
  """
  HOST_SYSTEM_UNKNOWN = ...
  HOST_SYSTEM_LINUX = ...
  HOST_SYSTEM_MAC = ...
  HOST_SYSTEM_WINDOWS = ...


_HOST_SYSTEM_BY_PLATFORM = ...
@dataclasses.dataclass
class BaseOptions:
  """Base options for MediaPipe Tasks' Python APIs.

  Represents external model asset used by the Task APIs. The files can be
  specified by one of the following two ways:

  (1) model asset file path in `model_asset_path`.
  (2) model asset contents loaded in `model_asset_buffer`.

  If more than one field of these fields is provided, they are used in this
  precedence order.

  Attributes:
    model_asset_path: Path to the model asset file.
    model_asset_buffer: The model asset file contents as bytes.
    delegate: Acceleration to use. Supported values are GPU and CPU. GPU support
      is currently limited to Ubuntu platforms.
  """
  class Delegate(enum.IntEnum):
    CPU = ...
    GPU = ...
  
  
  model_asset_path: Optional[str] = ...
  model_asset_buffer: Optional[bytes] = ...
  delegate: Optional[Delegate] = ...
  @doc_controls.do_not_generate_docs
  def to_ctypes(self) -> base_options_c_lib.MpBaseOptionsC:
    """Creates a MpBaseOptionsC struct from the BaseOptions object."""
    ...
  
  def __eq__(self, other: Any) -> bool:
    """Checks if this object is equal to the given object.

    Args:
      other: The object to be compared with.

    Returns:
      True if the objects are equal.
    """
    ...
  


