"""
This type stub file was generated by pyright.
"""

import ctypes
from typing import Any, List, Optional, Sequence
from mediapipe.tasks.python.core import mediapipe_c_utils, serial_dispatcher

"""MediaPipe Text tasks shared library."""
_BASE_LIB_PATH = ...
_shared_lib = ...
_CFunction = mediapipe_c_utils.CFunction
def load_raw_library(signatures: Sequence[_CFunction] = ..., lib_name: str = ...) -> ctypes.CDLL:
  """Loads the raw ctypes.CDLL shared library and registers signatures.

  This function loads the raw ctypes.CDLL shared library if it hasn't been
  loaded yet, otherwise it re-uses the existing instance. It attaches the
  provided signatures and makes them available across all callsites.

  Args:
    signatures: The ctypes function signatures to register in the library.
    lib_name: The name of the library to load. Defaults to 'mediapipe'.

  Returns:
    The ctypes shared library.
  """
  ...

def load_shared_library(signatures: Sequence[_CFunction] = ...) -> serial_dispatcher.SerialDispatcher:
  """Loads the shared library in a SerialDispatcher and registers signatures.

  This function creates a thread-safe wrapper for the shared library that
  dispatches all calls through a single dedicated thread. Every call to this
  function uses a different dispatch library with its own thread.

  Args:
    signatures: The ctypes function signatures to register in the library.

  Returns:
    A thread-safe wrapper for the ctypes shared library.
  """
  ...

def convert_strings_to_ctypes_array(str_list: Optional[List[str]]) -> Optional[Any]:
  """Converts a list of Python strings to a ctypes array of c_char_p.

  Args:
      str_list: A list of strings, or None.

  Returns:
      A ctypes array of c_char_p, or None if the input is None or empty.
  """
  ...

