"""
This type stub file was generated by pyright.
"""

import concurrent.futures
import ctypes
import dataclasses
import enum
from typing import Any, Callable, Optional, Sequence, Union

"""Common MediaPipe CTypes definitions and utilities."""
_shutdown = ...
_global_shutdown_lock = ...
def is_shutdown(): # -> bool:
  ...

@dataclasses.dataclass(frozen=True)
class CFunction:
  """Stores the ctypes signature information for a C function.

  Attributes:
    func_name: The name of the C function.
    argtypes: The ctypes types for the function arguments.
    restype: The ctypes type for the function's return value.
  """
  func_name: str
  argtypes: list[Any]
  restype: Any
  def create_python_wrapper(self, lib: ctypes.CDLL, executor: concurrent.futures.Executor) -> Callable[..., Any]:
    """Creates a callable wrapper that executes the C function on the executor.

    Args:
      lib: The ctypes shared library.
      executor: The executor to use for the C function.

    Returns:
      A callable that executes the C function on the executor.
    """
    ...
  


@dataclasses.dataclass(frozen=True)
class CStatusFunction(CFunction):
  """Stores the ctypes signature for a status-returning C function.

  The functions is required to take an error message argument as the last
  argument and return an `MpStatus' integer code.
  """
  def __init__(self, func_name: str, core_argtypes: Sequence[Any]) -> None:
    """Initializes the CStatusFunction.

    Args:
      func_name: The name of the C function.
      core_argtypes: The ctypes types for the function arguments excluding the
        error message argument.
    """
    ...
  
  def create_python_wrapper(self, lib: ctypes.CDLL, executor: concurrent.futures.Executor) -> Callable[..., None]:
    """Creates a callable wrapper that executes the C function on the executor.

    This function raises a Python exception based on the MpStatus code returned
    by the C API function and the error message argument.

    Args:
      lib: The ctypes shared library.
      executor: The executor to use for the C function.

    Returns:
      A callable that executes the C function on the executor.
    """
    ...
  


class MpStatus(enum.IntEnum):
  """Status codes for MediaPipe C API functions."""
  MP_OK = ...
  MP_CANCELLED = ...
  MP_UNKNOWN = ...
  MP_INVALID_ARGUMENT = ...
  MP_DEADLINE_EXCEEDED = ...
  MP_NOT_FOUND = ...
  MP_ALREADY_EXISTS = ...
  MP_PERMISSION_DENIED = ...
  MP_RESOURCE_EXHAUSTED = ...
  MP_FAILED_PRECONDITION = ...
  MP_ABORTED = ...
  MP_OUT_OF_RANGE = ...
  MP_UNIMPLEMENTED = ...
  MP_INTERNAL = ...
  MP_UNAVAILABLE = ...
  MP_DATA_LOSS = ...
  MP_UNAUTHENTICATED = ...


def convert_to_exception(status: int, error_message: Optional[ctypes.c_char_p] = ...) -> Union[Exception, None]:
  """Returns an exception based on the MpStatus code, or None if MP_OK."""
  ...

def handle_status(status: int, error_message: Optional[ctypes.c_char_p] = ...) -> None:
  """Checks the MpStatus and raises an error if not kMpOk.

  Args:
    status: The MpStatus code to check.
    error_message: The error message to use if an exception is raised. Uses a
      default error message if None.

  Raises:
    An error if the MpStatus is not kMpOk.
  """
  ...

