"""
This type stub file was generated by pyright.
"""

import ctypes
from typing import Sequence
from mediapipe.tasks.python.core import mediapipe_c_utils

"""A thread-safe dispatcher for a ctypes."""
class SerialDispatcher:
  """A wrapper class for a ctypes.CDLL object that serializes all calls.

  This ensures that functions from a non-thread-safe C library are called
  sequentially from a single dedicated thread, preventing race conditions
  and segmentation faults.

  If a function is a CStatusFunction, the dispatcher will raise a Python
  exception if the returned MpStatus code is not kMpOk.
  """
  _HAS_DYNAMIC_ATTRIBUTES = ...
  def __init__(self, lib: ctypes.CDLL, signatures: Sequence[mediapipe_c_utils.CFunction]) -> None:
    """Initializes the SerialDispatcher.

    Args:
      lib: The ctypes.CDLL object to wrap.
      signatures: the CFunction objects specifying the functions to wrap.
    """
    ...
  
  def close(self): # -> None:
    """Shuts down the dispatcher and waits for pending tasks to complete."""
    ...
  
  def __enter__(self): # -> Self:
    ...
  
  def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
    ...
  


