"""
This type stub file was generated by pyright.
"""

import ctypes

"""MediaPipe audio data ctypes."""
class MpAudioDataC(ctypes.Structure):
  """The audio data used in the C API."""
  _fields_ = ...


