"""
This type stub file was generated by pyright.
"""

import dataclasses
import numpy as np
from typing import Optional
from mediapipe.tasks.python.components.containers import audio_data_c
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""MediaPipe audio data."""
@dataclasses.dataclass
class AudioDataFormat:
  """Audio format metadata.

  Attributes:
    num_channels: the number of channels of the audio data.
    sample_rate: the audio sample rate.
  """
  num_channels: int = ...
  sample_rate: Optional[float] = ...


class AudioData:
  """MediaPipe Tasks' audio container."""
  def __init__(self, buffer_length: int, audio_format: AudioDataFormat = ...) -> None:
    """Initializes the `AudioData` object.

    Args:
      buffer_length: the length of the audio buffer.
      audio_format: the audio format metadata.
    """
    ...
  
  def clear(self): # -> None:
    """Clears the internal buffer and fill it with zeros."""
    ...
  
  def load_from_array(self, src: np.ndarray, offset: int = ..., size: int = ...) -> None:
    """Loads the audio data from a NumPy array.

    Args:
      src: A NumPy source array contains the input audio.
      offset: An optional offset for loading a slice of the `src` array to the
        buffer.
      size: An optional size parameter denoting the number of samples to load
        from the `src` array.

    Raises:
      ValueError: If the input array has an incorrect shape or if
        `offset` + `size` exceeds the length of the `src` array.
    """
    ...
  
  @classmethod
  def create_from_array(cls, src: np.ndarray, sample_rate: Optional[float] = ...) -> AudioData:
    """Creates an `AudioData` object from a NumPy array.

    Args:
      src: A NumPy source array contains the input audio.
      sample_rate: the optional audio sample rate.

    Returns:
      An `AudioData` object that contains a copy of the NumPy source array as
      the data.
    """
    ...
  
  @property
  def audio_format(self) -> AudioDataFormat:
    """Gets the audio format of the audio."""
    ...
  
  @property
  def buffer_length(self) -> int:
    """Gets the sample count of the audio."""
    ...
  
  @property
  def buffer(self) -> np.ndarray:
    """Gets the internal buffer."""
    ...
  
  @doc_controls.do_not_generate_docs
  def to_ctypes(self) -> audio_data_c.MpAudioDataC:
    """Converts the object to a ctypes audio data object."""
    ...
  


