"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any
from mediapipe.tasks.python.components.containers import rect_c as rect_c_lib
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""Bounding box data class."""
@dataclasses.dataclass
class BoundingBox:
  """An integer bounding box, axis aligned.

  Attributes:
    origin_x: The X coordinate of the top-left corner, in pixels.
    origin_y: The Y coordinate of the top-left corner, in pixels.
    width: The width of the bounding box, in pixels.
    height: The height of the bounding box, in pixels.
  """
  origin_x: int
  origin_y: int
  width: int
  height: int
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_obj: rect_c_lib.MpRectC) -> BoundingBox:
    """Creates a `BoundingBox` object from a ctypes MpRectC struct."""
    ...
  
  def __eq__(self, other: Any) -> bool:
    """Checks if this object is equal to the given object.

    Args:
      other: The object to be compared with.

    Returns:
      True if the objects are equal.
    """
    ...
  


