"""
This type stub file was generated by pyright.
"""

import ctypes

"""C types for MpCategory."""
class MpCategoryC(ctypes.Structure):
  """The ctypes struct for MpCategory."""
  _fields_ = ...


class MpCategoriesC(ctypes.Structure):
  """C types for a list of MpCategories."""
  _fields_ = ...


