"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, Optional
from mediapipe.tasks.python.components.containers import category_c as category_c_module
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""Category data class."""
@dataclasses.dataclass
class Category:
  """A classification category.

  Category is a util class, contains a label, its display name, a float
  value as score, and the index of the label in the corresponding label file.
  Typically it's used as the result of classification tasks.

  Attributes:
    index: The index of the label in the corresponding label file.
    score: The probability score of this label category.
    display_name: The display name of the label, which may be translated for
      different locales. For example, a label, "apple", may be translated into
      Spanish for display purpose, so that the `display_name` is "manzana".
    category_name: The label of this category object.
  """
  index: Optional[int] = ...
  score: Optional[float] = ...
  display_name: Optional[str] = ...
  category_name: Optional[str] = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_obj: category_c_module.MpCategoryC) -> Category:
    """Creates a `Category` object from the given `MpCategoryC` object.

    This function converts the `MpCategoryC` index of -1 to a Python value of
    None
    to retain the same semantic meaning. All other values are converted as-is.

    Args:
      c_obj: The `MpCategoryC` object to be converted.

    Returns:
      A `Category` object.
    """
    ...
  
  def __eq__(self, other: Any) -> bool:
    """Checks if this object is equal to the given object.

    Args:
      other: The object to be compared with.

    Returns:
      True if the objects are equal.
    """
    ...
  


@doc_controls.do_not_generate_docs
def create_list_of_categories_from_ctypes(c_obj: category_c_module.MpCategoriesC) -> list[Category]:
  """Creates a list of `Category` objects from a `MpCategoriesC` object."""
  ...

