"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, List, Optional
from mediapipe.tasks.python.components.containers import bounding_box as bounding_box_lib, category as category_lib, detections_c as detections_c_lib, keypoint as keypoint_lib
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""Detections data class."""
@dataclasses.dataclass
class Detection:
  """Represents one detected object in the object detector's results.

  Attributes:
    bounding_box: A BoundingBox object.
    categories: A list of Category objects.
    keypoints: A list of NormalizedKeypoint objects.
  """
  bounding_box: bounding_box_lib.BoundingBox
  categories: List[category_lib.Category]
  keypoints: Optional[List[keypoint_lib.NormalizedKeypoint]] = ...
  def __eq__(self, other: Any) -> bool:
    """Checks if this object is equal to the given object.

    Args:
      other: The object to be compared with.

    Returns:
      True if the objects are equal.
    """
    ...
  
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_obj: detections_c_lib.MpDetectionC) -> Detection:
    """Creates a `Detection` object from the given `MpDetectionC` object."""
    ...
  


@dataclasses.dataclass
class DetectionResult:
  """Represents the list of detected objects.

  Attributes:
    detections: A list of `Detection` objects.
  """
  detections: List[Detection]
  def __eq__(self, other: Any) -> bool:
    """Checks if this object is equal to the given object.

    Args:
      other: The object to be compared with.

    Returns:
      True if the objects are equal.
    """
    ...
  
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_obj: detections_c_lib.MpDetectionResultC) -> DetectionResult:
    """Creates a `DetectionResult` object from a `MpDetectionResultC` object."""
    ...
  


