"""
This type stub file was generated by pyright.
"""

import ctypes

"""MediaPipe Detection Result C API types."""
class MpDetectionC(ctypes.Structure):
  """CTypes for a single detection."""
  _fields_ = ...


class MpDetectionResultC(ctypes.Structure):
  """CTypes for the detection result."""
  _fields_ = ...


