"""
This type stub file was generated by pyright.
"""

import ctypes

"""MediaPipe Keypoint C API types."""
class MpNormalizedKeypointC(ctypes.Structure):
  """A keypoint in normalized coordinates."""
  _fields_ = ...


