"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, Optional
from mediapipe.tasks.python.components.containers import keypoint_c as keypoint_c_lib
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""Keypoint data class."""
@dataclasses.dataclass
class NormalizedKeypoint:
  """A normalized keypoint.

  Normalized keypoint represents a point in 2D space with x, y coordinates.
  x and y are normalized to [0.0, 1.0] by the image width and height
  respectively.

  Attributes:
    x: The x coordinates of the normalized keypoint.
    y: The y coordinates of the normalized keypoint.
    label: The optional label of the keypoint.
    score: The score of the keypoint.
  """
  x: Optional[float] = ...
  y: Optional[float] = ...
  label: Optional[str] = ...
  score: Optional[float] = ...
  @classmethod
  @doc_controls.do_not_generate_docs
  def from_ctypes(cls, c_obj: keypoint_c_lib.MpNormalizedKeypointC) -> NormalizedKeypoint:
    """Creates a `NormalizedKeypoint` object from a `MpNormalizedKeypointC."""
    ...
  
  def __eq__(self, other: Any) -> bool:
    """Checks if this object is equal to the given object.

    Args:
      other: The object to be compared with.

    Returns:
      True if the objects are equal.
    """
    ...
  


