"""
This type stub file was generated by pyright.
"""

import ctypes

"""C types for MpLandmark."""
class MpLandmarkC(ctypes.Structure):
  """The ctypes struct for MpLandmark."""
  _fields_ = ...


class MpLandmarksC(ctypes.Structure):
  """The ctypes struct for a list of MpLandmarks."""
  _fields_ = ...


class MpNormalizedLandmarkC(ctypes.Structure):
  """The ctypes struct for MpNormalizedLandmark."""
  _fields_ = ...


class MpNormalizedLandmarksC(ctypes.Structure):
  """The ctypes struct for a list of MpNormalizedLandmarks."""
  _fields_ = ...


