"""
This type stub file was generated by pyright.
"""

import ctypes
import numpy as np
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""C types for MpMatrix."""
class MpMatrixC(ctypes.Structure):
  """The ctypes struct for MpMatrix."""
  _fields_ = ...
  @doc_controls.do_not_generate_docs
  def to_numpy(self) -> np.ndarray:
    """Copies the MpMatrixC struct to a numpy array.

    The data is reshaped from column-major order to (cols, rows) and then
    transposed to a row-major numpy array. The underlying data is copied to
    ensure the data is not freed when the underlying C Matrix is closed.

    Returns:
      A numpy array representing the MpMatrixC struct.
    """
    ...
  


