"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import Any, Optional
from mediapipe.tasks.python.components.containers import rect_c as rect_c_module
from mediapipe.tasks.python.core.optional_dependencies import doc_controls

"""Rect data class."""
@dataclasses.dataclass
class Rect:
  """A rectangle, used as part of detection results.

  Absolute coordinates. The origin is on the top-left corner of the image.

  Attributes:
    left: The X coordinate of the left side of the rectangle.
    top: The Y coordinate of the top of the rectangle.
    bottom: The Y coordinate of the bottom of the rectangle.
    right: The X coordinate of the right side of the rectangle.
  """
  left: int
  top: int
  bottom: int
  right: int
  @doc_controls.do_not_generate_docs
  def to_ctypes(self) -> rect_c_module.MpRectC:
    """Generates a C API MpRectC object."""
    ...
  


@dataclasses.dataclass
class RectF:
  """A rectangle, used as part as input region-of-interest.

  The coordinates are normalized wrt the image dimensions, i.e. generally in
  [0,1] but they may exceed these bounds if describing a region overlapping the
  image. The origin is on the top-left corner of the image.

  Attributes:
    left: The X coordinate of the left side of the rectangle.
    top: The Y coordinate of the top of the rectangle.
    bottom: The Y coordinate of the bottom of the rectangle.
    right: The X coordinate of the right side of the rectangle.
  """
  left: float
  top: float
  bottom: float
  right: float
  @doc_controls.do_not_generate_docs
  def to_ctypes(self) -> rect_c_module.MpRectFC:
    """Generates a C API MpRectFC object."""
    ...
  


@dataclasses.dataclass
class NormalizedRect:
  """A rectangle with rotation in normalized coordinates.

  Location of the center of the rectangle in image coordinates. The (0.0, 0.0)
  point is at the (top, left) corner.

  The values of box center location and size are within [0, 1].

  Attributes:
    x_center: The normalized X coordinate of the rectangle, in image
      coordinates.
    y_center: The normalized Y coordinate of the rectangle, in image
      coordinates.
    width: The width of the rectangle.
    height: The height of the rectangle.
    rotation: Rotation angle is clockwise in radians.
    rect_id: Optional unique id to help associate different rectangles to each
      other.
  """
  x_center: float
  y_center: float
  width: float
  height: float
  rotation: Optional[float] = ...
  rect_id: Optional[int] = ...
  def __eq__(self, other: Any) -> bool:
    """Checks if this object is equal to the given object.

    Args:
      other: The object to be compared with.

    Returns:
      True if the objects are equal.
    """
    ...
  


