"""
This type stub file was generated by pyright.
"""

import ctypes

"""MediaPipe Rect C API types."""
class MpRectC(ctypes.Structure):
  """A rectangle, used as part of detection results."""
  _fields_ = ...


class MpRectFC(ctypes.Structure):
  """A rectangle (operating on floats), used as part of processing options."""
  _fields_ = ...


class MpNormalizedRectC(ctypes.Structure):
  """A rectangle with rotation in normalized coordinates."""
  _fields_ = ...


